
package is.netbokhald;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import is.netbokhald.li.Claim;
import is.netbokhald.li.ClaimCollection;
import is.netbokhald.li.ClaimInfo;
import is.netbokhald.li.ClaimKey;
import is.netbokhald.li.ClaimKeyCollection;
import is.netbokhald.li.ClaimOperationResult;
import is.netbokhald.li.ClaimsQuery;
import is.netbokhald.li.ClientPasswordCallback;
import is.netbokhald.li.IcelandicOnlineBankingClaimsService;
import is.netbokhald.li.IcelandicOnlineBankingClaimsSoap;
import is.netbokhald.li.PaymentsQuery;
import is.netbokhald.li.QueryClaimsResult;
import is.netbokhald.li.QueryPaymentsResult;

import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;

import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.ws.security.handler.WSHandlerConstants;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.072Z
 * Generated source version: 2.7.2
 * 
 */
public final class NetbokhaldClaimsProxy {

    private static final QName SERVICE_NAME = new QName("http://IcelandicOnlineBanking/2005/12/01/Claims", "IcelandicOnlineBankingClaimsService");
    private static IcelandicOnlineBankingClaimsSoap webservice;
    
    private NetbokhaldClaimsProxy() {
        URL wsdlURL = IcelandicOnlineBankingClaimsService.WSDL_LOCATION;

        IcelandicOnlineBankingClaimsService ss = new IcelandicOnlineBankingClaimsService(wsdlURL, SERVICE_NAME);
        webservice = ss.getIcelandicOnlineBankingClaimsSoap();  
        
        // http://cxf.apache.org/docs/ws-security.html
        org.apache.cxf.endpoint.Client client = ClientProxy.getClient(webservice);
        org.apache.cxf.endpoint.Endpoint cxfEndpoint = client.getEndpoint();
               
        // how to configure the incoming handler       
        Map<String,Object> inProps= new HashMap<String,Object>();
        
        // add the incoming handler
        WSS4JInInterceptor wssIn = new WSS4JInInterceptor(inProps);
        cxfEndpoint.getInInterceptors().add(wssIn);

        // how to configure the outgoing handler
        Map<String,Object> outProps = new HashMap<String,Object>();
        outProps.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);
                
        // Callback used to retrieve password for given user.
        outProps.put(WSHandlerConstants.PW_CALLBACK_CLASS, ClientPasswordCallback.class.getName());        
        outProps.put(WSHandlerConstants.ACTION, "Signature");
        outProps.put(WSHandlerConstants.USER, "myAlias");
        outProps.put(WSHandlerConstants.SIG_PROP_FILE, "client_sign.properties");

        // add the outgoing handler
        WSS4JOutInterceptor wssOut = new WSS4JOutInterceptor(outProps);
        cxfEndpoint.getOutInterceptors().add(wssOut);
    }

    public ClaimOperationResult createClaim(Claim claim) {
    	return webservice.createClaim(claim);
    }
    
    public String createClaims(ClaimCollection claims) {
    	return webservice.createClaims(claims);
    }
    
    public ClaimOperationResult cancelClaim(ClaimKey key) {
    	return webservice.cancelClaim(key);
    }

    public String cancelClaims(ClaimKeyCollection keys) {
    	return webservice.cancelClaims(keys);
    }
    
    public ClaimOperationResult alterClaim(Claim claim) {
    	return webservice.alterClaim(claim);
    }

    public String alterClaims(ClaimCollection claims) {
    	return webservice.alterClaims(claims);
    }

    public ClaimInfo queryClaim(ClaimKey key) {
    	return webservice.queryClaim(key);
    }
    
    public QueryClaimsResult queryClaims(ClaimsQuery keys) {
    	return webservice.queryClaims(keys);
    }

    public QueryPaymentsResult queryPayments(PaymentsQuery query) {
		return webservice.queryPayments(query);
	}

    public ClaimOperationResult getClaimOperationResult(String id) {
		return webservice.getClaimOperationResult(id);
	}

    public static void main(String args[]) throws java.lang.Exception {
    	NetbokhaldClaimsProxy claimsProxy = new NetbokhaldClaimsProxy();
    	
        {
        System.out.println("Invoking alterClaims...");
        is.netbokhald.li.ClaimCollection alterClaimsCollection = new is.netbokhald.li.ClaimCollection();
        java.util.List<is.netbokhald.li.Claim> alterClaimsList = new java.util.ArrayList<is.netbokhald.li.Claim>();
        is.netbokhald.li.Claim alterClaim = new is.netbokhald.li.Claim();
        
        is.netbokhald.li.ClaimKey alterClaimKey = new is.netbokhald.li.ClaimKey();
        alterClaimKey.setClaimantID("ClaimantID2080990424");
        alterClaimKey.setAccount("Account-1332676954");
        alterClaimKey.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.085Z"));
        alterClaim.setKey(alterClaimKey);
        
        alterClaim.setPayorID("PayorID-168320890");
        alterClaim.setCancellationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.085Z"));
        alterClaim.setIdentifier("Identifier-495304914");
        alterClaim.setAmount(new java.math.BigDecimal("7628769165356698033.6374715345028758739"));
        alterClaim.setReference("Reference-741059786");
        alterClaim.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.085Z"));
        alterClaim.setBillNumber("BillNumber-1791100261");
        alterClaim.setCustomerNumber("CustomerNumber1693365807");
        
        is.netbokhald.li.NoticeAndPaymentFee alterClaimNoticeAndPaymentFee = new is.netbokhald.li.NoticeAndPaymentFee();
        alterClaimNoticeAndPaymentFee.setPrinting(new java.math.BigDecimal("6663236068604432372.1156933907958960559"));
        alterClaimNoticeAndPaymentFee.setPaperless(new java.math.BigDecimal("7899737699759173222.6488588790356181101"));
        alterClaim.setNoticeAndPaymentFee(alterClaimNoticeAndPaymentFee);
        
        is.netbokhald.li.DateRestrictedCharge alterClaimsDefaultCharge = new is.netbokhald.li.DateRestrictedCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase alterClaimDefaultChargeFirst = null;
        alterClaimsDefaultCharge.setFirst(alterClaimDefaultChargeFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase alterClaimDefaultChargeSecond = null;
        alterClaimsDefaultCharge.setSecond(alterClaimDefaultChargeSecond);
        is.netbokhald.li.ReferenceDate alterClaimDefaultChargeReferenceDate = is.netbokhald.li.ReferenceDate.FINAL_DUE_DATE;
        alterClaimsDefaultCharge.setReferenceDate(alterClaimDefaultChargeReferenceDate);
        alterClaim.setDefaultCharge(alterClaimsDefaultCharge);
        
        alterClaim.setOtherCosts(new java.math.BigDecimal("-3966201441839425649.578160311865528957"));
        alterClaim.setOtherDefaultCosts(new java.math.BigDecimal("6855977244745943054.188525013259507291"));
        
        is.netbokhald.li.DefaultInterest alterClaimDefaultInterest = new is.netbokhald.li.DefaultInterest();
        is.netbokhald.li.DefaultInterestRule _alterClaims_claimsClaimVal1DefaultInterestRule = is.netbokhald.li.DefaultInterestRule.DEFAULT_INTEREST_AMOUNT_AND_DEFAULT_CHARGE;
        alterClaimDefaultInterest.setRule(_alterClaims_claimsClaimVal1DefaultInterestRule);
        alterClaimDefaultInterest.setPercentage4(new java.math.BigDecimal("-6347485276499945649.2660724297297657949"));
        alterClaimDefaultInterest.setSpecialCode("SpecialCode2126132998");
        alterClaim.setDefaultInterest(alterClaimDefaultInterest);
        
        is.netbokhald.li.CurrencyInformation alterClaimCurrencyInformation = new is.netbokhald.li.CurrencyInformation();
        alterClaimCurrencyInformation.setReferenceRate("ReferenceRate1661727159");
        alterClaimCurrencyInformation.setCurrency("Currency-1806953393");
        alterClaimCurrencyInformation.setPaymentRate("PaymentRate1626032486");
        alterClaim.setCurrencyInformation(alterClaimCurrencyInformation);
        
        alterClaim.setPermitOutOfSequencePayment(true);
        
        is.netbokhald.li.DiscountCharge alterClaimDiscount = new is.netbokhald.li.DiscountCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase alterClaimDiscountFirst = null;
        alterClaimDiscount.setFirst(alterClaimDiscountFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase alterClaimDiscountSecond = null;
        alterClaimDiscount.setSecond(alterClaimDiscountSecond);
        is.netbokhald.li.ReferenceDate alterClaimDiscountReferenceDate = is.netbokhald.li.ReferenceDate.FINAL_DUE_DATE;
        alterClaimDiscount.setReferenceDate(alterClaimDiscountReferenceDate);
        alterClaimDiscount.setIsPostRefDate(Boolean.valueOf(false));
        alterClaim.setDiscount(alterClaimDiscount);
        
        alterClaim.setIsPartialPaymentAllowed(false);
        
        is.netbokhald.li.BillPresentmentSystem alterClaimBillPresentmentSystem = new is.netbokhald.li.BillPresentmentSystem();
        alterClaimBillPresentmentSystem.setType("Type-1858462358");
        alterClaimBillPresentmentSystem.setParameters("Parameters2094739819");
        alterClaim.setBillPresentmentSystem(alterClaimBillPresentmentSystem);
        
        is.netbokhald.li.Printing alterClaimPrinting = new is.netbokhald.li.Printing();
        is.netbokhald.li.Address alterClaimPrintingClaimantAddress = new is.netbokhald.li.Address();
        alterClaimPrintingClaimantAddress.setName("Name130749674");
        alterClaimPrintingClaimantAddress.setAddressLine1("AddressLine1516059197");
        alterClaimPrintingClaimantAddress.setAddressLine2("AddressLine2-1875237451");
        alterClaimPrintingClaimantAddress.setPostCodeNumber("PostCodeNumber1776043607");
        alterClaimPrintingClaimantAddress.setCity("City993105661");
        alterClaimPrintingClaimantAddress.setRegion("Region6510666");
        alterClaimPrintingClaimantAddress.setCountry("Country-621966815");
        alterClaimPrinting.setClaimantAddress(alterClaimPrintingClaimantAddress);
        
        is.netbokhald.li.Address alterClaimPrintingPayorAddress = new is.netbokhald.li.Address();
        alterClaimPrintingPayorAddress.setName("Name1782904773");
        alterClaimPrintingPayorAddress.setAddressLine1("AddressLine11109643137");
        alterClaimPrintingPayorAddress.setAddressLine2("AddressLine2-1128386485");
        alterClaimPrintingPayorAddress.setPostCodeNumber("PostCodeNumber604408412");
        alterClaimPrintingPayorAddress.setCity("City-1699671873");
        alterClaimPrintingPayorAddress.setRegion("Region196876641");
        alterClaimPrintingPayorAddress.setCountry("Country1590377033");
        alterClaimPrinting.setPayorAddress(alterClaimPrintingPayorAddress);
        
        java.util.List<is.netbokhald.li.ItemRow> alterClaimPrintingItemRows = new java.util.ArrayList<is.netbokhald.li.ItemRow>();
        alterClaimPrinting.getItemRows().addAll(alterClaimPrintingItemRows);
        
        java.util.List<java.lang.String> alterClaimPrintingComments = new java.util.ArrayList<java.lang.String>();
        alterClaimPrinting.getComments().addAll(alterClaimPrintingComments);
        
        alterClaim.setPrinting(alterClaimPrinting);
        
        alterClaimsList.add(alterClaim);
        alterClaimsCollection.getClaim().addAll(alterClaimsList);
        java.lang.String alterClaimsReturn = claimsProxy.alterClaims(alterClaimsCollection);
        System.out.println("alterClaims.result=" + alterClaimsReturn);


        }
        {
        System.out.println("Invoking getClaimOperationResult...");
        java.lang.String _getClaimOperationResult_id = "_getClaimOperationResult_id-1107356201";
        is.netbokhald.li.ClaimOperationResult _getClaimOperationResult__return = claimsProxy.getClaimOperationResult(_getClaimOperationResult_id);
        System.out.println("getClaimOperationResult.result=" + _getClaimOperationResult__return);


        }
        {
        System.out.println("Invoking createClaim...");
        is.netbokhald.li.Claim _createClaim_claim = new is.netbokhald.li.Claim();
        is.netbokhald.li.ClaimKey _createClaim_claimKey = new is.netbokhald.li.ClaimKey();
        _createClaim_claimKey.setClaimantID("ClaimantID1541218");
        _createClaim_claimKey.setAccount("Account-1015967355");
        _createClaim_claimKey.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.088Z"));
        _createClaim_claim.setKey(_createClaim_claimKey);
        _createClaim_claim.setPayorID("PayorID-1926316274");
        _createClaim_claim.setCancellationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.089Z"));
        _createClaim_claim.setIdentifier("Identifier-515335222");
        _createClaim_claim.setAmount(new java.math.BigDecimal("-7297635092378906504.2778104166875506822"));
        _createClaim_claim.setReference("Reference1064202707");
        _createClaim_claim.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.089Z"));
        _createClaim_claim.setBillNumber("BillNumber-647587253");
        _createClaim_claim.setCustomerNumber("CustomerNumber-1087625191");
        is.netbokhald.li.NoticeAndPaymentFee _createClaim_claimNoticeAndPaymentFee = new is.netbokhald.li.NoticeAndPaymentFee();
        _createClaim_claimNoticeAndPaymentFee.setPrinting(new java.math.BigDecimal("-9033767035953067592.6726433116264363155"));
        _createClaim_claimNoticeAndPaymentFee.setPaperless(new java.math.BigDecimal("-8247242391533150181.6603698131929695345"));
        _createClaim_claim.setNoticeAndPaymentFee(_createClaim_claimNoticeAndPaymentFee);
        is.netbokhald.li.DateRestrictedCharge _createClaim_claimDefaultCharge = new is.netbokhald.li.DateRestrictedCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaim_claimDefaultChargeFirst = null;
        _createClaim_claimDefaultCharge.setFirst(_createClaim_claimDefaultChargeFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaim_claimDefaultChargeSecond = null;
        _createClaim_claimDefaultCharge.setSecond(_createClaim_claimDefaultChargeSecond);
        is.netbokhald.li.ReferenceDate _createClaim_claimDefaultChargeReferenceDate = is.netbokhald.li.ReferenceDate.FINAL_DUE_DATE;
        _createClaim_claimDefaultCharge.setReferenceDate(_createClaim_claimDefaultChargeReferenceDate);
        _createClaim_claim.setDefaultCharge(_createClaim_claimDefaultCharge);
        _createClaim_claim.setOtherCosts(new java.math.BigDecimal("-7769766050019894470.7294373982636964506"));
        _createClaim_claim.setOtherDefaultCosts(new java.math.BigDecimal("1939625599394765277.1865813317072852013"));
        is.netbokhald.li.DefaultInterest _createClaim_claimDefaultInterest = new is.netbokhald.li.DefaultInterest();
        is.netbokhald.li.DefaultInterestRule _createClaim_claimDefaultInterestRule = is.netbokhald.li.DefaultInterestRule.NO_DEFAULT_INTEREST;
        _createClaim_claimDefaultInterest.setRule(_createClaim_claimDefaultInterestRule);
        _createClaim_claimDefaultInterest.setPercentage4(new java.math.BigDecimal("-7175326857486028960.4219866018877983116"));
        _createClaim_claimDefaultInterest.setSpecialCode("SpecialCode-910445242");
        _createClaim_claim.setDefaultInterest(_createClaim_claimDefaultInterest);
        is.netbokhald.li.CurrencyInformation _createClaim_claimCurrencyInformation = new is.netbokhald.li.CurrencyInformation();
        _createClaim_claimCurrencyInformation.setReferenceRate("ReferenceRate1046577212");
        _createClaim_claimCurrencyInformation.setCurrency("Currency543021194");
        _createClaim_claimCurrencyInformation.setPaymentRate("PaymentRate673102798");
        _createClaim_claim.setCurrencyInformation(_createClaim_claimCurrencyInformation);
        _createClaim_claim.setPermitOutOfSequencePayment(false);
        is.netbokhald.li.DiscountCharge _createClaim_claimDiscount = new is.netbokhald.li.DiscountCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaim_claimDiscountFirst = null;
        _createClaim_claimDiscount.setFirst(_createClaim_claimDiscountFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaim_claimDiscountSecond = null;
        _createClaim_claimDiscount.setSecond(_createClaim_claimDiscountSecond);
        is.netbokhald.li.ReferenceDate _createClaim_claimDiscountReferenceDate = is.netbokhald.li.ReferenceDate.DUE_DATE;
        _createClaim_claimDiscount.setReferenceDate(_createClaim_claimDiscountReferenceDate);
        _createClaim_claimDiscount.setIsPostRefDate(Boolean.valueOf(true));
        _createClaim_claim.setDiscount(_createClaim_claimDiscount);
        _createClaim_claim.setIsPartialPaymentAllowed(true);
        is.netbokhald.li.BillPresentmentSystem _createClaim_claimBillPresentmentSystem = new is.netbokhald.li.BillPresentmentSystem();
        _createClaim_claimBillPresentmentSystem.setType("Type-1813339735");
        _createClaim_claimBillPresentmentSystem.setParameters("Parameters1968466722");
        _createClaim_claim.setBillPresentmentSystem(_createClaim_claimBillPresentmentSystem);
        is.netbokhald.li.Printing _createClaim_claimPrinting = new is.netbokhald.li.Printing();
        is.netbokhald.li.Address _createClaim_claimPrintingClaimantAddress = new is.netbokhald.li.Address();
        _createClaim_claimPrintingClaimantAddress.setName("Name1974393588");
        _createClaim_claimPrintingClaimantAddress.setAddressLine1("AddressLine1703841490");
        _createClaim_claimPrintingClaimantAddress.setAddressLine2("AddressLine2254866291");
        _createClaim_claimPrintingClaimantAddress.setPostCodeNumber("PostCodeNumber83691535");
        _createClaim_claimPrintingClaimantAddress.setCity("City-1829836575");
        _createClaim_claimPrintingClaimantAddress.setRegion("Region-1124111127");
        _createClaim_claimPrintingClaimantAddress.setCountry("Country1435469645");
        _createClaim_claimPrinting.setClaimantAddress(_createClaim_claimPrintingClaimantAddress);
        is.netbokhald.li.Address _createClaim_claimPrintingPayorAddress = new is.netbokhald.li.Address();
        _createClaim_claimPrintingPayorAddress.setName("Name227098835");
        _createClaim_claimPrintingPayorAddress.setAddressLine1("AddressLine1-1449981466");
        _createClaim_claimPrintingPayorAddress.setAddressLine2("AddressLine256486054");
        _createClaim_claimPrintingPayorAddress.setPostCodeNumber("PostCodeNumber-1517750187");
        _createClaim_claimPrintingPayorAddress.setCity("City1803350630");
        _createClaim_claimPrintingPayorAddress.setRegion("Region-106330732");
        _createClaim_claimPrintingPayorAddress.setCountry("Country2137390476");
        _createClaim_claimPrinting.setPayorAddress(_createClaim_claimPrintingPayorAddress);
        java.util.List<is.netbokhald.li.ItemRow> _createClaim_claimPrintingItemRows = new java.util.ArrayList<is.netbokhald.li.ItemRow>();
        is.netbokhald.li.ItemRow _createClaim_claimPrintingItemRowsVal1 = new is.netbokhald.li.ItemRow();
        _createClaim_claimPrintingItemRowsVal1.setText("Text-1716665505");
        _createClaim_claimPrintingItemRowsVal1.setAmount(new java.math.BigDecimal("401332566803305914.4004526912963607527"));
        _createClaim_claimPrintingItemRows.add(_createClaim_claimPrintingItemRowsVal1);
        _createClaim_claimPrinting.getItemRows().addAll(_createClaim_claimPrintingItemRows);
        java.util.List<java.lang.String> _createClaim_claimPrintingComments = new java.util.ArrayList<java.lang.String>();
        java.lang.String _createClaim_claimPrintingCommentsVal1 = "_createClaim_claimPrintingCommentsVal207441063";
        _createClaim_claimPrintingComments.add(_createClaim_claimPrintingCommentsVal1);
        _createClaim_claimPrinting.getComments().addAll(_createClaim_claimPrintingComments);
        _createClaim_claim.setPrinting(_createClaim_claimPrinting);
        is.netbokhald.li.ClaimOperationResult _createClaim__return = claimsProxy.createClaim(_createClaim_claim);
        System.out.println("createClaim.result=" + _createClaim__return);


        }
        {
        System.out.println("Invoking alterClaim...");
        is.netbokhald.li.Claim _alterClaim_claim = new is.netbokhald.li.Claim();
        is.netbokhald.li.ClaimKey _alterClaim_claimKey = new is.netbokhald.li.ClaimKey();
        _alterClaim_claimKey.setClaimantID("ClaimantID2051547694");
        _alterClaim_claimKey.setAccount("Account1343450535");
        _alterClaim_claimKey.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.092Z"));
        _alterClaim_claim.setKey(_alterClaim_claimKey);
        _alterClaim_claim.setPayorID("PayorID1104371823");
        _alterClaim_claim.setCancellationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.092Z"));
        _alterClaim_claim.setIdentifier("Identifier1560517200");
        _alterClaim_claim.setAmount(new java.math.BigDecimal("6953475140162571070.538806665234754776"));
        _alterClaim_claim.setReference("Reference-87021121");
        _alterClaim_claim.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.093Z"));
        _alterClaim_claim.setBillNumber("BillNumber1832348011");
        _alterClaim_claim.setCustomerNumber("CustomerNumber-1533813007");
        is.netbokhald.li.NoticeAndPaymentFee _alterClaim_claimNoticeAndPaymentFee = new is.netbokhald.li.NoticeAndPaymentFee();
        _alterClaim_claimNoticeAndPaymentFee.setPrinting(new java.math.BigDecimal("3810643880107335679.1915601054493728305"));
        _alterClaim_claimNoticeAndPaymentFee.setPaperless(new java.math.BigDecimal("-4284513597435777510.8263975040330789442"));
        _alterClaim_claim.setNoticeAndPaymentFee(_alterClaim_claimNoticeAndPaymentFee);
        is.netbokhald.li.DateRestrictedCharge _alterClaim_claimDefaultCharge = new is.netbokhald.li.DateRestrictedCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase _alterClaim_claimDefaultChargeFirst = null;
        _alterClaim_claimDefaultCharge.setFirst(_alterClaim_claimDefaultChargeFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase _alterClaim_claimDefaultChargeSecond = null;
        _alterClaim_claimDefaultCharge.setSecond(_alterClaim_claimDefaultChargeSecond);
        is.netbokhald.li.ReferenceDate _alterClaim_claimDefaultChargeReferenceDate = is.netbokhald.li.ReferenceDate.DUE_DATE;
        _alterClaim_claimDefaultCharge.setReferenceDate(_alterClaim_claimDefaultChargeReferenceDate);
        _alterClaim_claim.setDefaultCharge(_alterClaim_claimDefaultCharge);
        _alterClaim_claim.setOtherCosts(new java.math.BigDecimal("7341464659308143772.6206730315136164206"));
        _alterClaim_claim.setOtherDefaultCosts(new java.math.BigDecimal("-8975748457526841742.2329894347004123064"));
        is.netbokhald.li.DefaultInterest _alterClaim_claimDefaultInterest = new is.netbokhald.li.DefaultInterest();
        is.netbokhald.li.DefaultInterestRule _alterClaim_claimDefaultInterestRule = is.netbokhald.li.DefaultInterestRule.NO_DEFAULT_INTEREST;
        _alterClaim_claimDefaultInterest.setRule(_alterClaim_claimDefaultInterestRule);
        _alterClaim_claimDefaultInterest.setPercentage4(new java.math.BigDecimal("-6528512426342313475.3515060084157415757"));
        _alterClaim_claimDefaultInterest.setSpecialCode("SpecialCode-1231533733");
        _alterClaim_claim.setDefaultInterest(_alterClaim_claimDefaultInterest);
        is.netbokhald.li.CurrencyInformation _alterClaim_claimCurrencyInformation = new is.netbokhald.li.CurrencyInformation();
        _alterClaim_claimCurrencyInformation.setReferenceRate("ReferenceRate1585300105");
        _alterClaim_claimCurrencyInformation.setCurrency("Currency1897822768");
        _alterClaim_claimCurrencyInformation.setPaymentRate("PaymentRate-1687552165");
        _alterClaim_claim.setCurrencyInformation(_alterClaim_claimCurrencyInformation);
        _alterClaim_claim.setPermitOutOfSequencePayment(true);
        is.netbokhald.li.DiscountCharge _alterClaim_claimDiscount = new is.netbokhald.li.DiscountCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase _alterClaim_claimDiscountFirst = null;
        _alterClaim_claimDiscount.setFirst(_alterClaim_claimDiscountFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase _alterClaim_claimDiscountSecond = null;
        _alterClaim_claimDiscount.setSecond(_alterClaim_claimDiscountSecond);
        is.netbokhald.li.ReferenceDate _alterClaim_claimDiscountReferenceDate = is.netbokhald.li.ReferenceDate.FINAL_DUE_DATE;
        _alterClaim_claimDiscount.setReferenceDate(_alterClaim_claimDiscountReferenceDate);
        _alterClaim_claimDiscount.setIsPostRefDate(Boolean.valueOf(true));
        _alterClaim_claim.setDiscount(_alterClaim_claimDiscount);
        _alterClaim_claim.setIsPartialPaymentAllowed(true);
        is.netbokhald.li.BillPresentmentSystem _alterClaim_claimBillPresentmentSystem = new is.netbokhald.li.BillPresentmentSystem();
        _alterClaim_claimBillPresentmentSystem.setType("Type877164599");
        _alterClaim_claimBillPresentmentSystem.setParameters("Parameters1710942893");
        _alterClaim_claim.setBillPresentmentSystem(_alterClaim_claimBillPresentmentSystem);
        is.netbokhald.li.Printing _alterClaim_claimPrinting = new is.netbokhald.li.Printing();
        is.netbokhald.li.Address _alterClaim_claimPrintingClaimantAddress = new is.netbokhald.li.Address();
        _alterClaim_claimPrintingClaimantAddress.setName("Name926443995");
        _alterClaim_claimPrintingClaimantAddress.setAddressLine1("AddressLine1420613031");
        _alterClaim_claimPrintingClaimantAddress.setAddressLine2("AddressLine22017702517");
        _alterClaim_claimPrintingClaimantAddress.setPostCodeNumber("PostCodeNumber177455611");
        _alterClaim_claimPrintingClaimantAddress.setCity("City-1890199449");
        _alterClaim_claimPrintingClaimantAddress.setRegion("Region1308331184");
        _alterClaim_claimPrintingClaimantAddress.setCountry("Country214241147");
        _alterClaim_claimPrinting.setClaimantAddress(_alterClaim_claimPrintingClaimantAddress);
        is.netbokhald.li.Address _alterClaim_claimPrintingPayorAddress = new is.netbokhald.li.Address();
        _alterClaim_claimPrintingPayorAddress.setName("Name1155999843");
        _alterClaim_claimPrintingPayorAddress.setAddressLine1("AddressLine1-473818930");
        _alterClaim_claimPrintingPayorAddress.setAddressLine2("AddressLine2-1611330636");
        _alterClaim_claimPrintingPayorAddress.setPostCodeNumber("PostCodeNumber-169441285");
        _alterClaim_claimPrintingPayorAddress.setCity("City190683460");
        _alterClaim_claimPrintingPayorAddress.setRegion("Region-1676763909");
        _alterClaim_claimPrintingPayorAddress.setCountry("Country-1600621529");
        _alterClaim_claimPrinting.setPayorAddress(_alterClaim_claimPrintingPayorAddress);
        java.util.List<is.netbokhald.li.ItemRow> _alterClaim_claimPrintingItemRows = new java.util.ArrayList<is.netbokhald.li.ItemRow>();
        is.netbokhald.li.ItemRow _alterClaim_claimPrintingItemRowsVal1 = new is.netbokhald.li.ItemRow();
        _alterClaim_claimPrintingItemRowsVal1.setText("Text-1310555761");
        _alterClaim_claimPrintingItemRowsVal1.setAmount(new java.math.BigDecimal("-6578437477322552781.654778947732729322"));
        _alterClaim_claimPrintingItemRows.add(_alterClaim_claimPrintingItemRowsVal1);
        _alterClaim_claimPrinting.getItemRows().addAll(_alterClaim_claimPrintingItemRows);
        java.util.List<java.lang.String> _alterClaim_claimPrintingComments = new java.util.ArrayList<java.lang.String>();
        java.lang.String _alterClaim_claimPrintingCommentsVal1 = "_alterClaim_claimPrintingCommentsVal1392423663";
        _alterClaim_claimPrintingComments.add(_alterClaim_claimPrintingCommentsVal1);
        _alterClaim_claimPrinting.getComments().addAll(_alterClaim_claimPrintingComments);
        _alterClaim_claim.setPrinting(_alterClaim_claimPrinting);
        is.netbokhald.li.ClaimOperationResult _alterClaim__return = claimsProxy.alterClaim(_alterClaim_claim);
        System.out.println("alterClaim.result=" + _alterClaim__return);


        }
        {
        System.out.println("Invoking cancelClaim...");
        is.netbokhald.li.ClaimKey _cancelClaim_key = new is.netbokhald.li.ClaimKey();
        _cancelClaim_key.setClaimantID("ClaimantID1894452582");
        _cancelClaim_key.setAccount("Account-1785934483");
        _cancelClaim_key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.096Z"));
        is.netbokhald.li.ClaimOperationResult _cancelClaim__return = claimsProxy.cancelClaim(_cancelClaim_key);
        System.out.println("cancelClaim.result=" + _cancelClaim__return);


        }
        {
        System.out.println("Invoking createClaims...");
        is.netbokhald.li.ClaimCollection _createClaims_claims = new is.netbokhald.li.ClaimCollection();
        java.util.List<is.netbokhald.li.Claim> _createClaims_claimsClaim = new java.util.ArrayList<is.netbokhald.li.Claim>();
        is.netbokhald.li.Claim _createClaims_claimsClaimVal1 = new is.netbokhald.li.Claim();
        is.netbokhald.li.ClaimKey _createClaims_claimsClaimVal1Key = new is.netbokhald.li.ClaimKey();
        _createClaims_claimsClaimVal1Key.setClaimantID("ClaimantID1200728400");
        _createClaims_claimsClaimVal1Key.setAccount("Account1840672540");
        _createClaims_claimsClaimVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.097Z"));
        _createClaims_claimsClaimVal1.setKey(_createClaims_claimsClaimVal1Key);
        _createClaims_claimsClaimVal1.setPayorID("PayorID-1497620282");
        _createClaims_claimsClaimVal1.setCancellationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.097Z"));
        _createClaims_claimsClaimVal1.setIdentifier("Identifier-1810920708");
        _createClaims_claimsClaimVal1.setAmount(new java.math.BigDecimal("-784668366637347441.5854563641704642484"));
        _createClaims_claimsClaimVal1.setReference("Reference-1324292978");
        _createClaims_claimsClaimVal1.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.097Z"));
        _createClaims_claimsClaimVal1.setBillNumber("BillNumber-254328478");
        _createClaims_claimsClaimVal1.setCustomerNumber("CustomerNumber-1715896997");
        is.netbokhald.li.NoticeAndPaymentFee _createClaims_claimsClaimVal1NoticeAndPaymentFee = new is.netbokhald.li.NoticeAndPaymentFee();
        _createClaims_claimsClaimVal1NoticeAndPaymentFee.setPrinting(new java.math.BigDecimal("6634718919500319054.598657525118021870"));
        _createClaims_claimsClaimVal1NoticeAndPaymentFee.setPaperless(new java.math.BigDecimal("-2605582054771523953.1783949660728569174"));
        _createClaims_claimsClaimVal1.setNoticeAndPaymentFee(_createClaims_claimsClaimVal1NoticeAndPaymentFee);
        is.netbokhald.li.DateRestrictedCharge _createClaims_claimsClaimVal1DefaultCharge = new is.netbokhald.li.DateRestrictedCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaims_claimsClaimVal1DefaultChargeFirst = null;
        _createClaims_claimsClaimVal1DefaultCharge.setFirst(_createClaims_claimsClaimVal1DefaultChargeFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaims_claimsClaimVal1DefaultChargeSecond = null;
        _createClaims_claimsClaimVal1DefaultCharge.setSecond(_createClaims_claimsClaimVal1DefaultChargeSecond);
        is.netbokhald.li.ReferenceDate _createClaims_claimsClaimVal1DefaultChargeReferenceDate = is.netbokhald.li.ReferenceDate.DUE_DATE;
        _createClaims_claimsClaimVal1DefaultCharge.setReferenceDate(_createClaims_claimsClaimVal1DefaultChargeReferenceDate);
        _createClaims_claimsClaimVal1.setDefaultCharge(_createClaims_claimsClaimVal1DefaultCharge);
        _createClaims_claimsClaimVal1.setOtherCosts(new java.math.BigDecimal("5088746438104900904.7997538034582570576"));
        _createClaims_claimsClaimVal1.setOtherDefaultCosts(new java.math.BigDecimal("-6117319259866845154.1019969868606669799"));
        is.netbokhald.li.DefaultInterest _createClaims_claimsClaimVal1DefaultInterest = new is.netbokhald.li.DefaultInterest();
        is.netbokhald.li.DefaultInterestRule _createClaims_claimsClaimVal1DefaultInterestRule = is.netbokhald.li.DefaultInterestRule.NO_DEFAULT_INTEREST;
        _createClaims_claimsClaimVal1DefaultInterest.setRule(_createClaims_claimsClaimVal1DefaultInterestRule);
        _createClaims_claimsClaimVal1DefaultInterest.setPercentage4(new java.math.BigDecimal("-8706172789841655378.1522356484703826387"));
        _createClaims_claimsClaimVal1DefaultInterest.setSpecialCode("SpecialCode1202806190");
        _createClaims_claimsClaimVal1.setDefaultInterest(_createClaims_claimsClaimVal1DefaultInterest);
        is.netbokhald.li.CurrencyInformation _createClaims_claimsClaimVal1CurrencyInformation = new is.netbokhald.li.CurrencyInformation();
        _createClaims_claimsClaimVal1CurrencyInformation.setReferenceRate("ReferenceRate-574545158");
        _createClaims_claimsClaimVal1CurrencyInformation.setCurrency("Currency1919692408");
        _createClaims_claimsClaimVal1CurrencyInformation.setPaymentRate("PaymentRate-1354739663");
        _createClaims_claimsClaimVal1.setCurrencyInformation(_createClaims_claimsClaimVal1CurrencyInformation);
        _createClaims_claimsClaimVal1.setPermitOutOfSequencePayment(false);
        is.netbokhald.li.DiscountCharge _createClaims_claimsClaimVal1Discount = new is.netbokhald.li.DiscountCharge();
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaims_claimsClaimVal1DiscountFirst = null;
        _createClaims_claimsClaimVal1Discount.setFirst(_createClaims_claimsClaimVal1DiscountFirst);
        is.netbokhald.li.DiscountOrDefaultChargeBase _createClaims_claimsClaimVal1DiscountSecond = null;
        _createClaims_claimsClaimVal1Discount.setSecond(_createClaims_claimsClaimVal1DiscountSecond);
        is.netbokhald.li.ReferenceDate _createClaims_claimsClaimVal1DiscountReferenceDate = is.netbokhald.li.ReferenceDate.FINAL_DUE_DATE;
        _createClaims_claimsClaimVal1Discount.setReferenceDate(_createClaims_claimsClaimVal1DiscountReferenceDate);
        _createClaims_claimsClaimVal1Discount.setIsPostRefDate(Boolean.valueOf(false));
        _createClaims_claimsClaimVal1.setDiscount(_createClaims_claimsClaimVal1Discount);
        _createClaims_claimsClaimVal1.setIsPartialPaymentAllowed(false);
        is.netbokhald.li.BillPresentmentSystem _createClaims_claimsClaimVal1BillPresentmentSystem = new is.netbokhald.li.BillPresentmentSystem();
        _createClaims_claimsClaimVal1BillPresentmentSystem.setType("Type-1455340645");
        _createClaims_claimsClaimVal1BillPresentmentSystem.setParameters("Parameters-824138542");
        _createClaims_claimsClaimVal1.setBillPresentmentSystem(_createClaims_claimsClaimVal1BillPresentmentSystem);
        is.netbokhald.li.Printing _createClaims_claimsClaimVal1Printing = new is.netbokhald.li.Printing();
        is.netbokhald.li.Address _createClaims_claimsClaimVal1PrintingClaimantAddress = new is.netbokhald.li.Address();
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setName("Name-182916626");
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setAddressLine1("AddressLine1-966608457");
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setAddressLine2("AddressLine2-92762926");
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setPostCodeNumber("PostCodeNumber-1319607407");
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setCity("City143375128");
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setRegion("Region1642888800");
        _createClaims_claimsClaimVal1PrintingClaimantAddress.setCountry("Country716477547");
        _createClaims_claimsClaimVal1Printing.setClaimantAddress(_createClaims_claimsClaimVal1PrintingClaimantAddress);
        is.netbokhald.li.Address _createClaims_claimsClaimVal1PrintingPayorAddress = new is.netbokhald.li.Address();
        _createClaims_claimsClaimVal1PrintingPayorAddress.setName("Name-380960913");
        _createClaims_claimsClaimVal1PrintingPayorAddress.setAddressLine1("AddressLine1-1234386594");
        _createClaims_claimsClaimVal1PrintingPayorAddress.setAddressLine2("AddressLine2533699992");
        _createClaims_claimsClaimVal1PrintingPayorAddress.setPostCodeNumber("PostCodeNumber-1028154871");
        _createClaims_claimsClaimVal1PrintingPayorAddress.setCity("City-1148742838");
        _createClaims_claimsClaimVal1PrintingPayorAddress.setRegion("Region-2108551142");
        _createClaims_claimsClaimVal1PrintingPayorAddress.setCountry("Country-1867886323");
        _createClaims_claimsClaimVal1Printing.setPayorAddress(_createClaims_claimsClaimVal1PrintingPayorAddress);
        java.util.List<is.netbokhald.li.ItemRow> _createClaims_claimsClaimVal1PrintingItemRows = new java.util.ArrayList<is.netbokhald.li.ItemRow>();
        _createClaims_claimsClaimVal1Printing.getItemRows().addAll(_createClaims_claimsClaimVal1PrintingItemRows);
        java.util.List<java.lang.String> _createClaims_claimsClaimVal1PrintingComments = new java.util.ArrayList<java.lang.String>();
        _createClaims_claimsClaimVal1Printing.getComments().addAll(_createClaims_claimsClaimVal1PrintingComments);
        _createClaims_claimsClaimVal1.setPrinting(_createClaims_claimsClaimVal1Printing);
        _createClaims_claimsClaim.add(_createClaims_claimsClaimVal1);
        _createClaims_claims.getClaim().addAll(_createClaims_claimsClaim);
        java.lang.String _createClaims__return = claimsProxy.createClaims(_createClaims_claims);
        System.out.println("createClaims.result=" + _createClaims__return);


        }
        {
        System.out.println("Invoking queryPayments...");
        is.netbokhald.li.PaymentsQuery _queryPayments_query = new is.netbokhald.li.PaymentsQuery();
        _queryPayments_query.setClaimant("Claimant1757052810");
        _queryPayments_query.setIdentifier("Identifier1671432347");
        _queryPayments_query.setDisposalAccount("DisposalAccount-1591189150");
        _queryPayments_query.setTransactionDateFrom(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.101Z"));
        _queryPayments_query.setTransactionDateTo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.101Z"));
        _queryPayments_query.setEntryFrom(Long.valueOf(5875943819594960420l));
        _queryPayments_query.setEntryTo(Long.valueOf(5320967526212557269l));
        is.netbokhald.li.QueryPaymentsResult _queryPayments__return = claimsProxy.queryPayments(_queryPayments_query);
        System.out.println("queryPayments.result=" + _queryPayments__return);


        }
        {
        System.out.println("Invoking queryClaim...");
        is.netbokhald.li.ClaimKey _queryClaim_key = new is.netbokhald.li.ClaimKey();
        _queryClaim_key.setClaimantID("ClaimantID-1372164964");
        _queryClaim_key.setAccount("Account1725753802");
        _queryClaim_key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.102Z"));
        is.netbokhald.li.ClaimInfo _queryClaim__return = claimsProxy.queryClaim(_queryClaim_key);
        System.out.println("queryClaim.result=" + _queryClaim__return);


        }
        {
        System.out.println("Invoking cancelClaims...");
        is.netbokhald.li.ClaimKeyCollection _cancelClaims_keys = new is.netbokhald.li.ClaimKeyCollection();
        java.util.List<is.netbokhald.li.ClaimKey> _cancelClaims_keysClaimKey = new java.util.ArrayList<is.netbokhald.li.ClaimKey>();
        is.netbokhald.li.ClaimKey _cancelClaims_keysClaimKeyVal1 = new is.netbokhald.li.ClaimKey();
        _cancelClaims_keysClaimKeyVal1.setClaimantID("ClaimantID-1362712142");
        _cancelClaims_keysClaimKeyVal1.setAccount("Account-1336490857");
        _cancelClaims_keysClaimKeyVal1.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.102Z"));
        _cancelClaims_keysClaimKey.add(_cancelClaims_keysClaimKeyVal1);
        _cancelClaims_keys.getClaimKey().addAll(_cancelClaims_keysClaimKey);
        java.lang.String _cancelClaims__return = claimsProxy.cancelClaims(_cancelClaims_keys);
        System.out.println("cancelClaims.result=" + _cancelClaims__return);


        }
        {
        System.out.println("Invoking queryClaims...");
        is.netbokhald.li.ClaimsQuery _queryClaims_query = new is.netbokhald.li.ClaimsQuery();
        _queryClaims_query.setClaimant("Claimant117826536");
        _queryClaims_query.setIdentifier("Identifier1381816020");
        is.netbokhald.li.ClaimsQueryDateSpan _queryClaims_queryPeriod = new is.netbokhald.li.ClaimsQueryDateSpan();
        _queryClaims_queryPeriod.setDateFrom(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.103Z"));
        _queryClaims_queryPeriod.setDateTo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.103Z"));
        is.netbokhald.li.DateSpanReferenceDate _queryClaims_queryPeriodDateSpanReferenceDate = is.netbokhald.li.DateSpanReferenceDate.DUE_DATE;
        _queryClaims_queryPeriod.setDateSpanReferenceDate(_queryClaims_queryPeriodDateSpanReferenceDate);
        _queryClaims_query.setPeriod(_queryClaims_queryPeriod);
        _queryClaims_query.setPayor("Payor-1257272423");
        is.netbokhald.li.ClaimStatus _queryClaims_queryStatus = is.netbokhald.li.ClaimStatus.SECONDARY_COLLECTION;
        _queryClaims_query.setStatus(_queryClaims_queryStatus);
        _queryClaims_query.setEntryFrom(Long.valueOf(-7713481035717263832l));
        _queryClaims_query.setEntryTo(Long.valueOf(-2188907624719214632l));
        is.netbokhald.li.QueryClaimsResult _queryClaims__return = claimsProxy.queryClaims(_queryClaims_query);
        System.out.println("queryClaims.result=" + _queryClaims__return);


        }

        System.exit(0);
    }

}
