
package is.netbokhald;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import is.netbokhald.li.ClientPasswordCallback;
import is.netbokhald.li.IcelandicOnlineBankingPaymentsService;
import is.netbokhald.li.IcelandicOnlineBankingPaymentsSoap;
import is.netbokhald.li.Payment;
import is.netbokhald.li.Payments;
import is.netbokhald.li.PaymentsResult;
import is.netbokhald.li.PaymentsStatus;

import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;

import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.ws.security.handler.WSHandlerConstants;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.104Z
 * Generated source version: 2.7.2
 * 
 */
public final class NetbokhaldPaymentsProxy {

    private static final QName SERVICE_NAME = new QName("http://IcelandicOnlineBanking/2005/12/01/Payments", "IcelandicOnlineBankingPaymentsService");
    private static IcelandicOnlineBankingPaymentsSoap webservice;

    private NetbokhaldPaymentsProxy() {
        URL wsdlURL = IcelandicOnlineBankingPaymentsService.WSDL_LOCATION;

        IcelandicOnlineBankingPaymentsService ss = new IcelandicOnlineBankingPaymentsService(wsdlURL, SERVICE_NAME);
        webservice = ss.getIcelandicOnlineBankingPaymentsSoap();  
        
        // http://cxf.apache.org/docs/ws-security.html
        org.apache.cxf.endpoint.Client client = ClientProxy.getClient(webservice);
        org.apache.cxf.endpoint.Endpoint cxfEndpoint = client.getEndpoint();
               
        // how to configure the incoming handler       
        Map<String,Object> inProps= new HashMap<String,Object>();
        
        // add the incoming handler
        WSS4JInInterceptor wssIn = new WSS4JInInterceptor(inProps);
        cxfEndpoint.getInInterceptors().add(wssIn);

        // how to configure the outgoing handler
        Map<String,Object> outProps = new HashMap<String,Object>();
        outProps.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);
                
        // Callback used to retrieve password for given user.
        outProps.put(WSHandlerConstants.PW_CALLBACK_CLASS, ClientPasswordCallback.class.getName());        
        outProps.put(WSHandlerConstants.ACTION, "Signature");
        outProps.put(WSHandlerConstants.USER, "myAlias");
        outProps.put(WSHandlerConstants.SIG_PROP_FILE, "client_sign.properties");

        // add the outgoing handler
        WSS4JOutInterceptor wssOut = new WSS4JOutInterceptor(outProps);
        cxfEndpoint.getOutInterceptors().add(wssOut);
    }

	public PaymentsResult doPayment(Payment payment) {
		return webservice.doPayment(payment);
	}

	public String doPayments(Payments payments) {
		return webservice.doPayments(payments);
	}

	public PaymentsResult getPaymentResult(String paymentID) {
		return webservice.getPaymentResult(paymentID);
	}

	public PaymentsResult getPaymentsResult(String paymentID, PaymentsStatus filter) {
		return webservice.getPaymentsResult(paymentID, filter);
	}

    public static void main(String args[]) throws java.lang.Exception {
    	NetbokhaldPaymentsProxy paymentsProxy = new NetbokhaldPaymentsProxy();
    	
        {
        System.out.println("Invoking doPayment...");
        is.netbokhald.li.Payment _doPayment_payment = new is.netbokhald.li.Payment();
        is.netbokhald.li.PaymentOut _doPayment_paymentOut = new is.netbokhald.li.PaymentOut();
        _doPayment_paymentOut.setAccount("Account-1068574225");
        _doPayment_paymentOut.setAccountOwnerID("AccountOwnerID1213842617");
        _doPayment_paymentOut.setCategoryCode("CategoryCode1404815225");
        _doPayment_paymentOut.setReference("Reference1458322838");
        _doPayment_paymentOut.setBillNumber("BillNumber-417620771");
        is.netbokhald.li.Communication _doPayment_paymentOutReceipt = new is.netbokhald.li.Communication();
        is.netbokhald.li.Communication.PostalMail _doPayment_paymentOutReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
        _doPayment_paymentOutReceiptPostalMail.setLanguage("Language-683589119");
        is.netbokhald.li.Address _doPayment_paymentOutReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setName("Name-1007435750");
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine1963100197");
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine2-1745463824");
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber-686101285");
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setCity("City1623782091");
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setRegion("Region1338806462");
        _doPayment_paymentOutReceiptPostalMailReceiverAddress.setCountry("Country-106424634");
        _doPayment_paymentOutReceiptPostalMail.setReceiverAddress(_doPayment_paymentOutReceiptPostalMailReceiverAddress);
        _doPayment_paymentOutReceiptPostalMail.setUsePersonID(Boolean.valueOf(false));
        _doPayment_paymentOutReceipt.setPostalMail(_doPayment_paymentOutReceiptPostalMail);
        java.util.List<is.netbokhald.li.Communication.EMail> _doPayment_paymentOutReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
        _doPayment_paymentOutReceipt.getEMail().addAll(_doPayment_paymentOutReceiptEMail);
        java.util.List<is.netbokhald.li.Communication.SMS> _doPayment_paymentOutReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
        _doPayment_paymentOutReceipt.getSMS().addAll(_doPayment_paymentOutReceiptSMS);
        _doPayment_paymentOut.setReceipt(_doPayment_paymentOutReceipt);
        _doPayment_payment.setOut(_doPayment_paymentOut);
        is.netbokhald.li.PaymentIn _doPayment_paymentIn = new is.netbokhald.li.PaymentIn();
        is.netbokhald.li.ABGiro _doPayment_paymentInABGiro = new is.netbokhald.li.ABGiro();
        _doPayment_paymentInABGiro.setAccount("Account216613943");
        _doPayment_paymentInABGiro.setReference("Reference-1723861870");
        _doPayment_paymentInABGiro.setBillNumber("BillNumber-181153163");
        _doPayment_paymentInABGiro.setCategoryCode("CategoryCode401264150");
        _doPayment_paymentIn.setABGiro(_doPayment_paymentInABGiro);
        is.netbokhald.li.CGiro _doPayment_paymentInCGiro = new is.netbokhald.li.CGiro();
        _doPayment_paymentInCGiro.setAccount("Account442948268");
        _doPayment_paymentInCGiro.setAccountOwnerID("AccountOwnerID-931418813");
        _doPayment_paymentInCGiro.setBillNumber("BillNumber686019318");
        _doPayment_paymentInCGiro.setCategoryCode("CategoryCode-453742120");
        _doPayment_paymentIn.setCGiro(_doPayment_paymentInCGiro);
        is.netbokhald.li.PaymentSlip _doPayment_paymentInPaymentSlip = new is.netbokhald.li.PaymentSlip();
        _doPayment_paymentInPaymentSlip.setAccount("Account-682415071");
        _doPayment_paymentInPaymentSlip.setPersonID("PersonID-736456043");
        _doPayment_paymentInPaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.115Z"));
        _doPayment_paymentInPaymentSlip.setIsDeposit(true);
        _doPayment_paymentIn.setPaymentSlip(_doPayment_paymentInPaymentSlip);
        is.netbokhald.li.Transfer _doPayment_paymentInTransfer = new is.netbokhald.li.Transfer();
        _doPayment_paymentInTransfer.setAccount("Account1610476115");
        _doPayment_paymentInTransfer.setAccountOwnerID("AccountOwnerID-1292998534");
        _doPayment_paymentInTransfer.setCategoryCode("CategoryCode1408362341");
        _doPayment_paymentInTransfer.setReference("Reference-91209549");
        _doPayment_paymentInTransfer.setBillNumber("BillNumber1579662150");
        _doPayment_paymentIn.setTransfer(_doPayment_paymentInTransfer);
        _doPayment_paymentIn.setAmount(new java.math.BigDecimal("3309235370103974873.6278321109899019060"));
        is.netbokhald.li.Communication _doPayment_paymentInReceipt = new is.netbokhald.li.Communication();
        is.netbokhald.li.Communication.PostalMail _doPayment_paymentInReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
        _doPayment_paymentInReceiptPostalMail.setLanguage("Language-1335400872");
        is.netbokhald.li.Address _doPayment_paymentInReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setName("Name1899847384");
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine1896575397");
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine2142294005");
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber1294401829");
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setCity("City-1079123268");
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setRegion("Region1448696549");
        _doPayment_paymentInReceiptPostalMailReceiverAddress.setCountry("Country-1138470766");
        _doPayment_paymentInReceiptPostalMail.setReceiverAddress(_doPayment_paymentInReceiptPostalMailReceiverAddress);
        _doPayment_paymentInReceiptPostalMail.setUsePersonID(Boolean.valueOf(false));
        _doPayment_paymentInReceipt.setPostalMail(_doPayment_paymentInReceiptPostalMail);
        java.util.List<is.netbokhald.li.Communication.EMail> _doPayment_paymentInReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
        _doPayment_paymentInReceipt.getEMail().addAll(_doPayment_paymentInReceiptEMail);
        java.util.List<is.netbokhald.li.Communication.SMS> _doPayment_paymentInReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
        _doPayment_paymentInReceipt.getSMS().addAll(_doPayment_paymentInReceiptSMS);
        _doPayment_paymentIn.setReceipt(_doPayment_paymentInReceipt);
        _doPayment_paymentIn.setDescription("Description190609734");
        _doPayment_paymentIn.setBookingID("BookingID-1990242217");
        _doPayment_payment.setIn(_doPayment_paymentIn);
        _doPayment_payment.setDateOfForwardPayment(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.116Z"));
        is.netbokhald.li.PaymentsResult _doPayment__return = paymentsProxy.doPayment(_doPayment_payment);
        System.out.println("doPayment.result=" + _doPayment__return);


        }
        {
        System.out.println("Invoking getPaymentsResult...");
        java.lang.String _getPaymentsResult_paymentID = "_getPaymentsResult_paymentID-436519857";
        is.netbokhald.li.PaymentsStatus _getPaymentsResult_filter = is.netbokhald.li.PaymentsStatus.GET_OKAY;
        is.netbokhald.li.PaymentsResult _getPaymentsResult__return = paymentsProxy.getPaymentsResult(_getPaymentsResult_paymentID, _getPaymentsResult_filter);
        System.out.println("getPaymentsResult.result=" + _getPaymentsResult__return);


        }
        {
        System.out.println("Invoking getPaymentResult...");
        java.lang.String _getPaymentResult_paymentID = "_getPaymentResult_paymentID629148370";
        is.netbokhald.li.PaymentsResult _getPaymentResult__return = paymentsProxy.getPaymentResult(_getPaymentResult_paymentID);
        System.out.println("getPaymentResult.result=" + _getPaymentResult__return);


        }
        {
        System.out.println("Invoking doPayments...");
        is.netbokhald.li.Payments _doPayments_payments = new is.netbokhald.li.Payments();
        is.netbokhald.li.PaymentOut _doPayments_paymentsOut = new is.netbokhald.li.PaymentOut();
        _doPayments_paymentsOut.setAccount("Account1706966518");
        _doPayments_paymentsOut.setAccountOwnerID("AccountOwnerID-239311097");
        _doPayments_paymentsOut.setCategoryCode("CategoryCode1713916325");
        _doPayments_paymentsOut.setReference("Reference-620942133");
        _doPayments_paymentsOut.setBillNumber("BillNumber-1196475205");
        is.netbokhald.li.Communication _doPayments_paymentsOutReceipt = new is.netbokhald.li.Communication();
        is.netbokhald.li.Communication.PostalMail _doPayments_paymentsOutReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
        _doPayments_paymentsOutReceiptPostalMail.setLanguage("Language-321205165");
        is.netbokhald.li.Address _doPayments_paymentsOutReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setName("Name-1889253410");
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine1-1210541216");
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine2-529640897");
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber1555361380");
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setCity("City1732439982");
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setRegion("Region334174839");
        _doPayments_paymentsOutReceiptPostalMailReceiverAddress.setCountry("Country-908300125");
        _doPayments_paymentsOutReceiptPostalMail.setReceiverAddress(_doPayments_paymentsOutReceiptPostalMailReceiverAddress);
        _doPayments_paymentsOutReceiptPostalMail.setUsePersonID(Boolean.valueOf(false));
        _doPayments_paymentsOutReceipt.setPostalMail(_doPayments_paymentsOutReceiptPostalMail);
        java.util.List<is.netbokhald.li.Communication.EMail> _doPayments_paymentsOutReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
        _doPayments_paymentsOutReceipt.getEMail().addAll(_doPayments_paymentsOutReceiptEMail);
        java.util.List<is.netbokhald.li.Communication.SMS> _doPayments_paymentsOutReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
        _doPayments_paymentsOutReceipt.getSMS().addAll(_doPayments_paymentsOutReceiptSMS);
        _doPayments_paymentsOut.setReceipt(_doPayments_paymentsOutReceipt);
        _doPayments_payments.setOut(_doPayments_paymentsOut);
        java.util.List<is.netbokhald.li.PaymentIn> _doPayments_paymentsIn = new java.util.ArrayList<is.netbokhald.li.PaymentIn>();
        is.netbokhald.li.PaymentIn _doPayments_paymentsInVal1 = new is.netbokhald.li.PaymentIn();
        is.netbokhald.li.ABGiro _doPayments_paymentsInVal1ABGiro = new is.netbokhald.li.ABGiro();
        _doPayments_paymentsInVal1ABGiro.setAccount("Account1277319547");
        _doPayments_paymentsInVal1ABGiro.setReference("Reference-1052904990");
        _doPayments_paymentsInVal1ABGiro.setBillNumber("BillNumber-580448077");
        _doPayments_paymentsInVal1ABGiro.setCategoryCode("CategoryCode340592692");
        _doPayments_paymentsInVal1.setABGiro(_doPayments_paymentsInVal1ABGiro);
        is.netbokhald.li.CGiro _doPayments_paymentsInVal1CGiro = new is.netbokhald.li.CGiro();
        _doPayments_paymentsInVal1CGiro.setAccount("Account-81887235");
        _doPayments_paymentsInVal1CGiro.setAccountOwnerID("AccountOwnerID2000058576");
        _doPayments_paymentsInVal1CGiro.setBillNumber("BillNumber-422786487");
        _doPayments_paymentsInVal1CGiro.setCategoryCode("CategoryCode-681621454");
        _doPayments_paymentsInVal1.setCGiro(_doPayments_paymentsInVal1CGiro);
        is.netbokhald.li.PaymentSlip _doPayments_paymentsInVal1PaymentSlip = new is.netbokhald.li.PaymentSlip();
        _doPayments_paymentsInVal1PaymentSlip.setAccount("Account-1020810937");
        _doPayments_paymentsInVal1PaymentSlip.setPersonID("PersonID-47553403");
        _doPayments_paymentsInVal1PaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.119Z"));
        _doPayments_paymentsInVal1PaymentSlip.setIsDeposit(false);
        _doPayments_paymentsInVal1.setPaymentSlip(_doPayments_paymentsInVal1PaymentSlip);
        is.netbokhald.li.Transfer _doPayments_paymentsInVal1Transfer = new is.netbokhald.li.Transfer();
        _doPayments_paymentsInVal1Transfer.setAccount("Account-552869929");
        _doPayments_paymentsInVal1Transfer.setAccountOwnerID("AccountOwnerID589814791");
        _doPayments_paymentsInVal1Transfer.setCategoryCode("CategoryCode979226189");
        _doPayments_paymentsInVal1Transfer.setReference("Reference891513544");
        _doPayments_paymentsInVal1Transfer.setBillNumber("BillNumber1592368235");
        _doPayments_paymentsInVal1.setTransfer(_doPayments_paymentsInVal1Transfer);
        _doPayments_paymentsInVal1.setAmount(new java.math.BigDecimal("-814055267988200275.4195402468193955584"));
        is.netbokhald.li.Communication _doPayments_paymentsInVal1Receipt = new is.netbokhald.li.Communication();
        is.netbokhald.li.Communication.PostalMail _doPayments_paymentsInVal1ReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
        _doPayments_paymentsInVal1ReceiptPostalMail.setLanguage("Language1099477256");
        is.netbokhald.li.Address _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setName("Name855931868");
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine1560508576");
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine2-1202938356");
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber2128477847");
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setCity("City363917681");
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setRegion("Region-2109119658");
        _doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress.setCountry("Country-2052563400");
        _doPayments_paymentsInVal1ReceiptPostalMail.setReceiverAddress(_doPayments_paymentsInVal1ReceiptPostalMailReceiverAddress);
        _doPayments_paymentsInVal1ReceiptPostalMail.setUsePersonID(Boolean.valueOf(true));
        _doPayments_paymentsInVal1Receipt.setPostalMail(_doPayments_paymentsInVal1ReceiptPostalMail);
        java.util.List<is.netbokhald.li.Communication.EMail> _doPayments_paymentsInVal1ReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
        _doPayments_paymentsInVal1Receipt.getEMail().addAll(_doPayments_paymentsInVal1ReceiptEMail);
        java.util.List<is.netbokhald.li.Communication.SMS> _doPayments_paymentsInVal1ReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
        _doPayments_paymentsInVal1Receipt.getSMS().addAll(_doPayments_paymentsInVal1ReceiptSMS);
        _doPayments_paymentsInVal1.setReceipt(_doPayments_paymentsInVal1Receipt);
        _doPayments_paymentsInVal1.setDescription("Description1577064285");
        _doPayments_paymentsInVal1.setBookingID("BookingID1292416566");
        _doPayments_paymentsIn.add(_doPayments_paymentsInVal1);
        _doPayments_payments.getIn().addAll(_doPayments_paymentsIn);
        _doPayments_payments.setDateOfForwardPayment(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.121Z"));
        _doPayments_payments.setNameOfBatch("NameOfBatch330927222");
        _doPayments_payments.setRollbackOnError(false);
        _doPayments_payments.setIsOneToMany(false);
        java.lang.String _doPayments__return = paymentsProxy.doPayments(_doPayments_payments);
        System.out.println("doPayments.result=" + _doPayments__return);


        }

        System.exit(0);
    }

}
