package is.netbokhald.li;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.201Z
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", name = "IcelandicOnlineBankingPaymentsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IcelandicOnlineBankingPaymentsSoap {

    @WebResult(name = "paymentsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
    @RequestWrapper(localName = "DoPayment", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.DoPayment")
    @WebMethod(operationName = "DoPayment", action = "http://IcelandicOnlineBanking/2005/12/01/DoPayment")
    @ResponseWrapper(localName = "DoPaymentResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.DoPaymentResponse")
    public is.netbokhald.li.PaymentsResult doPayment(
        @WebParam(name = "payment", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
        is.netbokhald.li.Payment payment
    );

    @WebResult(name = "paymentsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
    @RequestWrapper(localName = "GetPaymentsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.GetPaymentsResult")
    @WebMethod(operationName = "GetPaymentsResult", action = "http://IcelandicOnlineBanking/2005/12/01/GetPaymentsResult")
    @ResponseWrapper(localName = "GetPaymentsResultResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.GetPaymentsResultResponse")
    public is.netbokhald.li.PaymentsResult getPaymentsResult(
        @WebParam(name = "paymentID", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
        java.lang.String paymentID,
        @WebParam(name = "filter", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
        is.netbokhald.li.PaymentsStatus filter
    );

    @WebResult(name = "paymentsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
    @RequestWrapper(localName = "GetPaymentResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.GetPaymentResult")
    @WebMethod(operationName = "GetPaymentResult", action = "http://IcelandicOnlineBanking/2005/12/01/GetPaymentResult")
    @ResponseWrapper(localName = "GetPaymentResultResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.GetPaymentResultResponse")
    public is.netbokhald.li.PaymentsResult getPaymentResult(
        @WebParam(name = "paymentID", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
        java.lang.String paymentID
    );

    @WebResult(name = "paymentsID", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
    @RequestWrapper(localName = "DoPayments", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.DoPayments")
    @WebMethod(operationName = "DoPayments", action = "http://IcelandicOnlineBanking/2005/12/01/DoPayments")
    @ResponseWrapper(localName = "DoPaymentsResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments", className = "is.netbokhald.li.DoPaymentsResponse")
    public java.lang.String doPayments(
        @WebParam(name = "payments", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments")
        is.netbokhald.li.Payments payments
    );
}
