
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package is.netbokhald.li;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.135Z
 * Generated source version: 2.7.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "IcelandicOnlineBankingClaimsService",
                      portName = "IcelandicOnlineBankingClaimsSoap",
                      targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims",
                      wsdlLocation = "https://b2bws.fbl.is/xsd/IcelandicOnlineBanking.wsdl",
                      endpointInterface = "is.netbokhald.li.IcelandicOnlineBankingClaimsSoap")
                      
public class IcelandicOnlineBankingClaimsSoapImpl implements IcelandicOnlineBankingClaimsSoap {

    private static final Logger LOG = Logger.getLogger(IcelandicOnlineBankingClaimsSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#alterClaims(is.netbokhald.li.ClaimCollection  claims )*
     */
    public java.lang.String alterClaims(is.netbokhald.li.ClaimCollection claims) { 
        LOG.info("Executing operation alterClaims");
        System.out.println(claims);
        try {
            java.lang.String _return = "_return-1965298663";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#getClaimOperationResult(java.lang.String  id )*
     */
    public is.netbokhald.li.ClaimOperationResult getClaimOperationResult(java.lang.String id) { 
        LOG.info("Executing operation getClaimOperationResult");
        System.out.println(id);
        try {
            is.netbokhald.li.ClaimOperationResult _return = new is.netbokhald.li.ClaimOperationResult();
            _return.setID("ID1432475140");
            is.netbokhald.li.BatchStatus2 _returnStatus = is.netbokhald.li.BatchStatus2.NOT_CONFIRMED;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.ClaimResult> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.ClaimResult>();
            is.netbokhald.li.ClaimResult _returnSuccessVal1 = new is.netbokhald.li.ClaimResult();
            is.netbokhald.li.ClaimKey _returnSuccessVal1Key = new is.netbokhald.li.ClaimKey();
            _returnSuccessVal1Key.setClaimantID("ClaimantID-349908282");
            _returnSuccessVal1Key.setAccount("Account216156181");
            _returnSuccessVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.146Z"));
            _returnSuccessVal1.setKey(_returnSuccessVal1Key);
            is.netbokhald.li.PrintInformation _returnSuccessVal1Print = is.netbokhald.li.PrintInformation.NO_INFORMATION;
            _returnSuccessVal1.setPrint(_returnSuccessVal1Print);
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.ClaimError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.ClaimError>();
            is.netbokhald.li.ClaimError _returnErrorsVal1 = new is.netbokhald.li.ClaimError();
            is.netbokhald.li.ClaimKey _returnErrorsVal1Key = new is.netbokhald.li.ClaimKey();
            _returnErrorsVal1Key.setClaimantID("ClaimantID-2108049310");
            _returnErrorsVal1Key.setAccount("Account2119382949");
            _returnErrorsVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.146Z"));
            _returnErrorsVal1.setKey(_returnErrorsVal1Key);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code2144986301");
            _returnErrorsVal1Error.setMessage("Message-312420934");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#createClaim(is.netbokhald.li.Claim  claim )*
     */
    public is.netbokhald.li.ClaimOperationResult createClaim(is.netbokhald.li.Claim claim) { 
        LOG.info("Executing operation createClaim");
        System.out.println(claim);
        try {
            is.netbokhald.li.ClaimOperationResult _return = new is.netbokhald.li.ClaimOperationResult();
            _return.setID("ID506071468");
            is.netbokhald.li.BatchStatus2 _returnStatus = is.netbokhald.li.BatchStatus2.COMPLETED;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.ClaimResult> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.ClaimResult>();
            is.netbokhald.li.ClaimResult _returnSuccessVal1 = new is.netbokhald.li.ClaimResult();
            is.netbokhald.li.ClaimKey _returnSuccessVal1Key = new is.netbokhald.li.ClaimKey();
            _returnSuccessVal1Key.setClaimantID("ClaimantID-1968292768");
            _returnSuccessVal1Key.setAccount("Account1679706499");
            _returnSuccessVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.147Z"));
            _returnSuccessVal1.setKey(_returnSuccessVal1Key);
            is.netbokhald.li.PrintInformation _returnSuccessVal1Print = is.netbokhald.li.PrintInformation.DIRECT_PAYMENT_CLAIM;
            _returnSuccessVal1.setPrint(_returnSuccessVal1Print);
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.ClaimError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.ClaimError>();
            is.netbokhald.li.ClaimError _returnErrorsVal1 = new is.netbokhald.li.ClaimError();
            is.netbokhald.li.ClaimKey _returnErrorsVal1Key = new is.netbokhald.li.ClaimKey();
            _returnErrorsVal1Key.setClaimantID("ClaimantID218960816");
            _returnErrorsVal1Key.setAccount("Account-1422411770");
            _returnErrorsVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.148Z"));
            _returnErrorsVal1.setKey(_returnErrorsVal1Key);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code1279598746");
            _returnErrorsVal1Error.setMessage("Message-559882786");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#alterClaim(is.netbokhald.li.Claim  claim )*
     */
    public is.netbokhald.li.ClaimOperationResult alterClaim(is.netbokhald.li.Claim claim) { 
        LOG.info("Executing operation alterClaim");
        System.out.println(claim);
        try {
            is.netbokhald.li.ClaimOperationResult _return = new is.netbokhald.li.ClaimOperationResult();
            _return.setID("ID1899842829");
            is.netbokhald.li.BatchStatus2 _returnStatus = is.netbokhald.li.BatchStatus2.NOT_CONFIRMED;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.ClaimResult> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.ClaimResult>();
            is.netbokhald.li.ClaimResult _returnSuccessVal1 = new is.netbokhald.li.ClaimResult();
            is.netbokhald.li.ClaimKey _returnSuccessVal1Key = new is.netbokhald.li.ClaimKey();
            _returnSuccessVal1Key.setClaimantID("ClaimantID-35108630");
            _returnSuccessVal1Key.setAccount("Account924699808");
            _returnSuccessVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.149Z"));
            _returnSuccessVal1.setKey(_returnSuccessVal1Key);
            is.netbokhald.li.PrintInformation _returnSuccessVal1Print = is.netbokhald.li.PrintInformation.INTERNET_BANKING_CLAIM;
            _returnSuccessVal1.setPrint(_returnSuccessVal1Print);
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.ClaimError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.ClaimError>();
            is.netbokhald.li.ClaimError _returnErrorsVal1 = new is.netbokhald.li.ClaimError();
            is.netbokhald.li.ClaimKey _returnErrorsVal1Key = new is.netbokhald.li.ClaimKey();
            _returnErrorsVal1Key.setClaimantID("ClaimantID1894849774");
            _returnErrorsVal1Key.setAccount("Account-2113343113");
            _returnErrorsVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.150Z"));
            _returnErrorsVal1.setKey(_returnErrorsVal1Key);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code-1523254154");
            _returnErrorsVal1Error.setMessage("Message1985569070");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#cancelClaim(is.netbokhald.li.ClaimKey  key )*
     */
    public is.netbokhald.li.ClaimOperationResult cancelClaim(is.netbokhald.li.ClaimKey key) { 
        LOG.info("Executing operation cancelClaim");
        System.out.println(key);
        try {
            is.netbokhald.li.ClaimOperationResult _return = new is.netbokhald.li.ClaimOperationResult();
            _return.setID("ID390765693");
            is.netbokhald.li.BatchStatus2 _returnStatus = is.netbokhald.li.BatchStatus2.COMPLETED_WITH_ERRORS;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.ClaimResult> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.ClaimResult>();
            is.netbokhald.li.ClaimResult _returnSuccessVal1 = new is.netbokhald.li.ClaimResult();
            is.netbokhald.li.ClaimKey _returnSuccessVal1Key = new is.netbokhald.li.ClaimKey();
            _returnSuccessVal1Key.setClaimantID("ClaimantID263740515");
            _returnSuccessVal1Key.setAccount("Account1844214710");
            _returnSuccessVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.150Z"));
            _returnSuccessVal1.setKey(_returnSuccessVal1Key);
            is.netbokhald.li.PrintInformation _returnSuccessVal1Print = is.netbokhald.li.PrintInformation.NO_INFORMATION;
            _returnSuccessVal1.setPrint(_returnSuccessVal1Print);
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.ClaimError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.ClaimError>();
            is.netbokhald.li.ClaimError _returnErrorsVal1 = new is.netbokhald.li.ClaimError();
            is.netbokhald.li.ClaimKey _returnErrorsVal1Key = new is.netbokhald.li.ClaimKey();
            _returnErrorsVal1Key.setClaimantID("ClaimantID1514655446");
            _returnErrorsVal1Key.setAccount("Account-1059643257");
            _returnErrorsVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.151Z"));
            _returnErrorsVal1.setKey(_returnErrorsVal1Key);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code743805520");
            _returnErrorsVal1Error.setMessage("Message-2134797974");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#createClaims(is.netbokhald.li.ClaimCollection  claims )*
     */
    public java.lang.String createClaims(is.netbokhald.li.ClaimCollection claims) { 
        LOG.info("Executing operation createClaims");
        System.out.println(claims);
        try {
            java.lang.String _return = "_return794885517";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#queryPayments(is.netbokhald.li.PaymentsQuery  query )*
     */
    public is.netbokhald.li.QueryPaymentsResult queryPayments(is.netbokhald.li.PaymentsQuery query) { 
        LOG.info("Executing operation queryPayments");
        System.out.println(query);
        try {
            is.netbokhald.li.QueryPaymentsResult _return = new is.netbokhald.li.QueryPaymentsResult();
            _return.setTotalCount(-4162229800207937473l);
            java.util.List<is.netbokhald.li.Payment2> _returnPayments = new java.util.ArrayList<is.netbokhald.li.Payment2>();
            is.netbokhald.li.Payment2 _returnPaymentsVal1 = new is.netbokhald.li.Payment2();
            is.netbokhald.li.ClaimKey _returnPaymentsVal1Key = new is.netbokhald.li.ClaimKey();
            _returnPaymentsVal1Key.setClaimantID("ClaimantID-275032558");
            _returnPaymentsVal1Key.setAccount("Account-1150235278");
            _returnPaymentsVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.152Z"));
            _returnPaymentsVal1.setKey(_returnPaymentsVal1Key);
            _returnPaymentsVal1.setPayorID("PayorID775833926");
            _returnPaymentsVal1.setAmount(new java.math.BigDecimal("7785786146298242029.5573267062617579030"));
            _returnPaymentsVal1.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.153Z"));
            _returnPaymentsVal1.setIdentifier("Identifier1746306594");
            _returnPaymentsVal1.setReference("Reference227523669");
            _returnPaymentsVal1.setCategoryCode("CategoryCode1074700987");
            _returnPaymentsVal1.setRedeemingBank("RedeemingBank-1439262066");
            _returnPaymentsVal1.setTransactionDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.153Z"));
            _returnPaymentsVal1.setBookingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.153Z"));
            _returnPaymentsVal1.setValueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.153Z"));
            _returnPaymentsVal1.setPaymentType("PaymentType-713725796");
            _returnPaymentsVal1.setAmountDeposited(new java.math.BigDecimal("3476231073026147452.5429559776771219546"));
            _returnPaymentsVal1.setTotalAmount(new java.math.BigDecimal("6188369483066738513.163311163529535656"));
            _returnPaymentsVal1.setCapitalGainsTax(new java.math.BigDecimal("141190867740523671.7068129246459898739"));
            _returnPaymentsVal1.setBillNumber("BillNumber-1267959065");
            _returnPaymentsVal1.setCustomerNumber("CustomerNumber-80287346");
            _returnPaymentsVal1.setNoticeChargeAmount(new java.math.BigDecimal("-305910157701401795.4425941693733135794"));
            _returnPaymentsVal1.setDefaultChargeAmount(new java.math.BigDecimal("4828029745071594512.3548563644765892602"));
            _returnPaymentsVal1.setOtherCostsAmount(new java.math.BigDecimal("200753486923373925.7419270993830600245"));
            _returnPaymentsVal1.setOtherDefaultCostsAmount(new java.math.BigDecimal("2955248666953874790.8013843679086130220"));
            _returnPaymentsVal1.setDefaultInterestAmount(new java.math.BigDecimal("3940263180033639105.1545458876213381845"));
            _returnPaymentsVal1.setDiscountAmount(new java.math.BigDecimal("-8336443720771883074.9137703148733670512"));
            is.netbokhald.li.CurrencyExchangeRate _returnPaymentsVal1Currency = new is.netbokhald.li.CurrencyExchangeRate();
            _returnPaymentsVal1Currency.setCurrency("Currency289479588");
            _returnPaymentsVal1Currency.setRate(new java.math.BigDecimal("7749950120191181830.7760635455556599398"));
            _returnPaymentsVal1.setCurrency(_returnPaymentsVal1Currency);
            _returnPaymentsVal1.setBatchNumber("BatchNumber-972589322");
            _returnPayments.add(_returnPaymentsVal1);
            _return.getPayments().addAll(_returnPayments);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#queryClaim(is.netbokhald.li.ClaimKey  key )*
     */
    public is.netbokhald.li.ClaimInfo queryClaim(is.netbokhald.li.ClaimKey key) { 
        LOG.info("Executing operation queryClaim");
        System.out.println(key);
        try {
            is.netbokhald.li.ClaimInfo _return = new is.netbokhald.li.ClaimInfo();
            is.netbokhald.li.ClaimKey _returnKey = new is.netbokhald.li.ClaimKey();
            _returnKey.setClaimantID("ClaimantID1314605630");
            _returnKey.setAccount("Account-1958240941");
            _returnKey.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.155Z"));
            _return.setKey(_returnKey);
            _return.setPayorID("PayorID1519883237");
            _return.setCancellationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.155Z"));
            _return.setIdentifier("Identifier2112300276");
            _return.setAmount(new java.math.BigDecimal("9038763554263154985.7259680766032664833"));
            _return.setReference("Reference-159021619");
            _return.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.155Z"));
            _return.setBillNumber("BillNumber325611897");
            _return.setCustomerNumber("CustomerNumber339344277");
            is.netbokhald.li.NoticeAndPaymentFee _returnNoticeAndPaymentFee = new is.netbokhald.li.NoticeAndPaymentFee();
            _returnNoticeAndPaymentFee.setPrinting(new java.math.BigDecimal("1748295294074713050.2001137339598734088"));
            _returnNoticeAndPaymentFee.setPaperless(new java.math.BigDecimal("-6771781742841883978.3708723126382000"));
            _return.setNoticeAndPaymentFee(_returnNoticeAndPaymentFee);
            is.netbokhald.li.DateRestrictedCharge _returnDefaultCharge = new is.netbokhald.li.DateRestrictedCharge();
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnDefaultChargeFirst = null;
            _returnDefaultCharge.setFirst(_returnDefaultChargeFirst);
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnDefaultChargeSecond = null;
            _returnDefaultCharge.setSecond(_returnDefaultChargeSecond);
            is.netbokhald.li.ReferenceDate _returnDefaultChargeReferenceDate = is.netbokhald.li.ReferenceDate.FINAL_DUE_DATE;
            _returnDefaultCharge.setReferenceDate(_returnDefaultChargeReferenceDate);
            _return.setDefaultCharge(_returnDefaultCharge);
            _return.setOtherCosts(new java.math.BigDecimal("8779427427165575069.3394132382889588405"));
            _return.setOtherDefaultCosts(new java.math.BigDecimal("-1407171325341369254.1866564277152330054"));
            is.netbokhald.li.DefaultInterest _returnDefaultInterest = new is.netbokhald.li.DefaultInterest();
            is.netbokhald.li.DefaultInterestRule _returnDefaultInterestRule = is.netbokhald.li.DefaultInterestRule.NO_DEFAULT_INTEREST;
            _returnDefaultInterest.setRule(_returnDefaultInterestRule);
            _returnDefaultInterest.setPercentage4(new java.math.BigDecimal("-7481295669529484693.8423766665472209217"));
            _returnDefaultInterest.setSpecialCode("SpecialCode-1289415345");
            _return.setDefaultInterest(_returnDefaultInterest);
            is.netbokhald.li.CurrencyInformation _returnCurrencyInformation = new is.netbokhald.li.CurrencyInformation();
            _returnCurrencyInformation.setReferenceRate("ReferenceRate-270427330");
            _returnCurrencyInformation.setCurrency("Currency-1814254883");
            _returnCurrencyInformation.setPaymentRate("PaymentRate922119921");
            _return.setCurrencyInformation(_returnCurrencyInformation);
            _return.setPermitOutOfSequencePayment(false);
            is.netbokhald.li.DiscountCharge _returnDiscount = new is.netbokhald.li.DiscountCharge();
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnDiscountFirst = null;
            _returnDiscount.setFirst(_returnDiscountFirst);
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnDiscountSecond = null;
            _returnDiscount.setSecond(_returnDiscountSecond);
            is.netbokhald.li.ReferenceDate _returnDiscountReferenceDate = is.netbokhald.li.ReferenceDate.DUE_DATE;
            _returnDiscount.setReferenceDate(_returnDiscountReferenceDate);
            _returnDiscount.setIsPostRefDate(Boolean.valueOf(false));
            _return.setDiscount(_returnDiscount);
            _return.setIsPartialPaymentAllowed(false);
            is.netbokhald.li.BillPresentmentSystem _returnBillPresentmentSystem = new is.netbokhald.li.BillPresentmentSystem();
            _returnBillPresentmentSystem.setType("Type-1192773095");
            _returnBillPresentmentSystem.setParameters("Parameters1507777626");
            _return.setBillPresentmentSystem(_returnBillPresentmentSystem);
            is.netbokhald.li.Printing _returnPrinting = new is.netbokhald.li.Printing();
            is.netbokhald.li.Address _returnPrintingClaimantAddress = new is.netbokhald.li.Address();
            _returnPrintingClaimantAddress.setName("Name-542036123");
            _returnPrintingClaimantAddress.setAddressLine1("AddressLine1-255549239");
            _returnPrintingClaimantAddress.setAddressLine2("AddressLine2-1212810886");
            _returnPrintingClaimantAddress.setPostCodeNumber("PostCodeNumber1085239684");
            _returnPrintingClaimantAddress.setCity("City19585537");
            _returnPrintingClaimantAddress.setRegion("Region-409804199");
            _returnPrintingClaimantAddress.setCountry("Country-864875626");
            _returnPrinting.setClaimantAddress(_returnPrintingClaimantAddress);
            is.netbokhald.li.Address _returnPrintingPayorAddress = new is.netbokhald.li.Address();
            _returnPrintingPayorAddress.setName("Name978592817");
            _returnPrintingPayorAddress.setAddressLine1("AddressLine11086745709");
            _returnPrintingPayorAddress.setAddressLine2("AddressLine2-2013643971");
            _returnPrintingPayorAddress.setPostCodeNumber("PostCodeNumber1135565436");
            _returnPrintingPayorAddress.setCity("City-556906287");
            _returnPrintingPayorAddress.setRegion("Region-607153880");
            _returnPrintingPayorAddress.setCountry("Country236465217");
            _returnPrinting.setPayorAddress(_returnPrintingPayorAddress);
            java.util.List<is.netbokhald.li.ItemRow> _returnPrintingItemRows = new java.util.ArrayList<is.netbokhald.li.ItemRow>();
            is.netbokhald.li.ItemRow _returnPrintingItemRowsVal1 = new is.netbokhald.li.ItemRow();
            _returnPrintingItemRowsVal1.setText("Text-491508775");
            _returnPrintingItemRowsVal1.setAmount(new java.math.BigDecimal("-7583727042887150119.3805304230512756888"));
            _returnPrintingItemRows.add(_returnPrintingItemRowsVal1);
            _returnPrinting.getItemRows().addAll(_returnPrintingItemRows);
            java.util.List<java.lang.String> _returnPrintingComments = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPrintingCommentsVal1 = "_returnPrintingCommentsVal-1601032172";
            _returnPrintingComments.add(_returnPrintingCommentsVal1);
            _returnPrinting.getComments().addAll(_returnPrintingComments);
            _return.setPrinting(_returnPrinting);
            is.netbokhald.li.ClaimStatus _returnStatus = is.netbokhald.li.ClaimStatus.UNPAID;
            _return.setStatus(_returnStatus);
            _return.setCategoryCode("CategoryCode-1784941897");
            _return.setTotalAmountDue(new java.math.BigDecimal("6086386919719516777.4789820513973317350"));
            _return.setNoticeChargeAmount(new java.math.BigDecimal("-6716424157109489761.5824770736064124549"));
            _return.setDefaultChargeAmount(new java.math.BigDecimal("-2835466763112069229.131250834923316545"));
            _return.setOtherCostsAmount(new java.math.BigDecimal("-7978574549281785300.1073441280276418387"));
            _return.setOtherDefaultCostsAmount(new java.math.BigDecimal("3260430815044700679.2226068195989475977"));
            _return.setDefaultInterestAmount(new java.math.BigDecimal("-3181239974994045610.8496092363893033609"));
            _return.setDiscountAmount(new java.math.BigDecimal("4749010841107648773.200253275976215350"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#cancelClaims(is.netbokhald.li.ClaimKeyCollection  keys )*
     */
    public java.lang.String cancelClaims(is.netbokhald.li.ClaimKeyCollection keys) { 
        LOG.info("Executing operation cancelClaims");
        System.out.println(keys);
        try {
            java.lang.String _return = "_return168786527";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingClaimsSoap#queryClaims(is.netbokhald.li.ClaimsQuery  query )*
     */
    public is.netbokhald.li.QueryClaimsResult queryClaims(is.netbokhald.li.ClaimsQuery query) { 
        LOG.info("Executing operation queryClaims");
        System.out.println(query);
        try {
            is.netbokhald.li.QueryClaimsResult _return = new is.netbokhald.li.QueryClaimsResult();
            _return.setTotalCount(-2786089772922829520l);
            java.util.List<is.netbokhald.li.ClaimInfo> _returnClaims = new java.util.ArrayList<is.netbokhald.li.ClaimInfo>();
            is.netbokhald.li.ClaimInfo _returnClaimsVal1 = new is.netbokhald.li.ClaimInfo();
            is.netbokhald.li.ClaimKey _returnClaimsVal1Key = new is.netbokhald.li.ClaimKey();
            _returnClaimsVal1Key.setClaimantID("ClaimantID-153823896");
            _returnClaimsVal1Key.setAccount("Account1783399048");
            _returnClaimsVal1Key.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.159Z"));
            _returnClaimsVal1.setKey(_returnClaimsVal1Key);
            _returnClaimsVal1.setPayorID("PayorID61016429");
            _returnClaimsVal1.setCancellationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.159Z"));
            _returnClaimsVal1.setIdentifier("Identifier1668654311");
            _returnClaimsVal1.setAmount(new java.math.BigDecimal("-8224682636935966996.4914388827965665889"));
            _returnClaimsVal1.setReference("Reference-1957037374");
            _returnClaimsVal1.setFinalDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.160Z"));
            _returnClaimsVal1.setBillNumber("BillNumber-105691817");
            _returnClaimsVal1.setCustomerNumber("CustomerNumber-526004665");
            is.netbokhald.li.NoticeAndPaymentFee _returnClaimsVal1NoticeAndPaymentFee = new is.netbokhald.li.NoticeAndPaymentFee();
            _returnClaimsVal1NoticeAndPaymentFee.setPrinting(new java.math.BigDecimal("-7210914227137171966.5117919396713754745"));
            _returnClaimsVal1NoticeAndPaymentFee.setPaperless(new java.math.BigDecimal("-4192656912067386771.6022481354414421701"));
            _returnClaimsVal1.setNoticeAndPaymentFee(_returnClaimsVal1NoticeAndPaymentFee);
            is.netbokhald.li.DateRestrictedCharge _returnClaimsVal1DefaultCharge = new is.netbokhald.li.DateRestrictedCharge();
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnClaimsVal1DefaultChargeFirst = null;
            _returnClaimsVal1DefaultCharge.setFirst(_returnClaimsVal1DefaultChargeFirst);
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnClaimsVal1DefaultChargeSecond = null;
            _returnClaimsVal1DefaultCharge.setSecond(_returnClaimsVal1DefaultChargeSecond);
            is.netbokhald.li.ReferenceDate _returnClaimsVal1DefaultChargeReferenceDate = is.netbokhald.li.ReferenceDate.DUE_DATE;
            _returnClaimsVal1DefaultCharge.setReferenceDate(_returnClaimsVal1DefaultChargeReferenceDate);
            _returnClaimsVal1.setDefaultCharge(_returnClaimsVal1DefaultCharge);
            _returnClaimsVal1.setOtherCosts(new java.math.BigDecimal("4058920500363838749.8893754388577184737"));
            _returnClaimsVal1.setOtherDefaultCosts(new java.math.BigDecimal("-7202612870234258544.5451990972547959231"));
            is.netbokhald.li.DefaultInterest _returnClaimsVal1DefaultInterest = new is.netbokhald.li.DefaultInterest();
            is.netbokhald.li.DefaultInterestRule _returnClaimsVal1DefaultInterestRule = is.netbokhald.li.DefaultInterestRule.DEFAULT_INTEREST_AMOUNT_AND_DEFAULT_CHARGE;
            _returnClaimsVal1DefaultInterest.setRule(_returnClaimsVal1DefaultInterestRule);
            _returnClaimsVal1DefaultInterest.setPercentage4(new java.math.BigDecimal("8834169963537814544.4283108891262264348"));
            _returnClaimsVal1DefaultInterest.setSpecialCode("SpecialCode1719947797");
            _returnClaimsVal1.setDefaultInterest(_returnClaimsVal1DefaultInterest);
            is.netbokhald.li.CurrencyInformation _returnClaimsVal1CurrencyInformation = new is.netbokhald.li.CurrencyInformation();
            _returnClaimsVal1CurrencyInformation.setReferenceRate("ReferenceRate927220819");
            _returnClaimsVal1CurrencyInformation.setCurrency("Currency858702807");
            _returnClaimsVal1CurrencyInformation.setPaymentRate("PaymentRate-508822099");
            _returnClaimsVal1.setCurrencyInformation(_returnClaimsVal1CurrencyInformation);
            _returnClaimsVal1.setPermitOutOfSequencePayment(false);
            is.netbokhald.li.DiscountCharge _returnClaimsVal1Discount = new is.netbokhald.li.DiscountCharge();
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnClaimsVal1DiscountFirst = null;
            _returnClaimsVal1Discount.setFirst(_returnClaimsVal1DiscountFirst);
            is.netbokhald.li.DiscountOrDefaultChargeBase _returnClaimsVal1DiscountSecond = null;
            _returnClaimsVal1Discount.setSecond(_returnClaimsVal1DiscountSecond);
            is.netbokhald.li.ReferenceDate _returnClaimsVal1DiscountReferenceDate = is.netbokhald.li.ReferenceDate.DUE_DATE;
            _returnClaimsVal1Discount.setReferenceDate(_returnClaimsVal1DiscountReferenceDate);
            _returnClaimsVal1Discount.setIsPostRefDate(Boolean.valueOf(true));
            _returnClaimsVal1.setDiscount(_returnClaimsVal1Discount);
            _returnClaimsVal1.setIsPartialPaymentAllowed(false);
            is.netbokhald.li.BillPresentmentSystem _returnClaimsVal1BillPresentmentSystem = new is.netbokhald.li.BillPresentmentSystem();
            _returnClaimsVal1BillPresentmentSystem.setType("Type-1747952571");
            _returnClaimsVal1BillPresentmentSystem.setParameters("Parameters221390206");
            _returnClaimsVal1.setBillPresentmentSystem(_returnClaimsVal1BillPresentmentSystem);
            is.netbokhald.li.Printing _returnClaimsVal1Printing = new is.netbokhald.li.Printing();
            is.netbokhald.li.Address _returnClaimsVal1PrintingClaimantAddress = new is.netbokhald.li.Address();
            _returnClaimsVal1PrintingClaimantAddress.setName("Name-1095866686");
            _returnClaimsVal1PrintingClaimantAddress.setAddressLine1("AddressLine11257564892");
            _returnClaimsVal1PrintingClaimantAddress.setAddressLine2("AddressLine21598250930");
            _returnClaimsVal1PrintingClaimantAddress.setPostCodeNumber("PostCodeNumber-699723278");
            _returnClaimsVal1PrintingClaimantAddress.setCity("City-574608461");
            _returnClaimsVal1PrintingClaimantAddress.setRegion("Region556935277");
            _returnClaimsVal1PrintingClaimantAddress.setCountry("Country811062897");
            _returnClaimsVal1Printing.setClaimantAddress(_returnClaimsVal1PrintingClaimantAddress);
            is.netbokhald.li.Address _returnClaimsVal1PrintingPayorAddress = new is.netbokhald.li.Address();
            _returnClaimsVal1PrintingPayorAddress.setName("Name298938325");
            _returnClaimsVal1PrintingPayorAddress.setAddressLine1("AddressLine1200385920");
            _returnClaimsVal1PrintingPayorAddress.setAddressLine2("AddressLine2395776052");
            _returnClaimsVal1PrintingPayorAddress.setPostCodeNumber("PostCodeNumber-1348792272");
            _returnClaimsVal1PrintingPayorAddress.setCity("City-1234678821");
            _returnClaimsVal1PrintingPayorAddress.setRegion("Region-1316956044");
            _returnClaimsVal1PrintingPayorAddress.setCountry("Country-569871438");
            _returnClaimsVal1Printing.setPayorAddress(_returnClaimsVal1PrintingPayorAddress);
            java.util.List<is.netbokhald.li.ItemRow> _returnClaimsVal1PrintingItemRows = new java.util.ArrayList<is.netbokhald.li.ItemRow>();
            _returnClaimsVal1Printing.getItemRows().addAll(_returnClaimsVal1PrintingItemRows);
            java.util.List<java.lang.String> _returnClaimsVal1PrintingComments = new java.util.ArrayList<java.lang.String>();
            _returnClaimsVal1Printing.getComments().addAll(_returnClaimsVal1PrintingComments);
            _returnClaimsVal1.setPrinting(_returnClaimsVal1Printing);
            is.netbokhald.li.ClaimStatus _returnClaimsVal1Status = is.netbokhald.li.ClaimStatus.UNPAID;
            _returnClaimsVal1.setStatus(_returnClaimsVal1Status);
            _returnClaimsVal1.setCategoryCode("CategoryCode-1361433162");
            _returnClaimsVal1.setTotalAmountDue(new java.math.BigDecimal("5056129392699399056.6949488222989277838"));
            _returnClaimsVal1.setNoticeChargeAmount(new java.math.BigDecimal("-19843099169854053.8342748474735801566"));
            _returnClaimsVal1.setDefaultChargeAmount(new java.math.BigDecimal("-8494971310677741809.8951804777655462724"));
            _returnClaimsVal1.setOtherCostsAmount(new java.math.BigDecimal("-5032041126376429801.6837340597082446271"));
            _returnClaimsVal1.setOtherDefaultCostsAmount(new java.math.BigDecimal("8678279908916667796.9135156840253915169"));
            _returnClaimsVal1.setDefaultInterestAmount(new java.math.BigDecimal("-1433331168070585827.4273232500799098916"));
            _returnClaimsVal1.setDiscountAmount(new java.math.BigDecimal("936899026561132358.1022572229437495572"));
            _returnClaims.add(_returnClaimsVal1);
            _return.getClaims().addAll(_returnClaims);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
