package is.netbokhald.li;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.233Z
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "IcelandicOnlineBankingPaymentsService", 
                  wsdlLocation = "https://b2bws.fbl.is/xsd/IcelandicOnlineBanking.wsdl",
                  targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments") 
public class IcelandicOnlineBankingPaymentsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://IcelandicOnlineBanking/2005/12/01/Payments", "IcelandicOnlineBankingPaymentsService");
    public final static QName IcelandicOnlineBankingPaymentsSoap = new QName("http://IcelandicOnlineBanking/2005/12/01/Payments", "IcelandicOnlineBankingPaymentsSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://b2bws.fbl.is/xsd/IcelandicOnlineBanking.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IcelandicOnlineBankingPaymentsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://b2bws.fbl.is/xsd/IcelandicOnlineBanking.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IcelandicOnlineBankingPaymentsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IcelandicOnlineBankingPaymentsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IcelandicOnlineBankingPaymentsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IcelandicOnlineBankingPaymentsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IcelandicOnlineBankingPaymentsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IcelandicOnlineBankingPaymentsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IcelandicOnlineBankingPaymentsSoap
     */
    @WebEndpoint(name = "IcelandicOnlineBankingPaymentsSoap")
    public IcelandicOnlineBankingPaymentsSoap getIcelandicOnlineBankingPaymentsSoap() {
        return super.getPort(IcelandicOnlineBankingPaymentsSoap, IcelandicOnlineBankingPaymentsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IcelandicOnlineBankingPaymentsSoap
     */
    @WebEndpoint(name = "IcelandicOnlineBankingPaymentsSoap")
    public IcelandicOnlineBankingPaymentsSoap getIcelandicOnlineBankingPaymentsSoap(WebServiceFeature... features) {
        return super.getPort(IcelandicOnlineBankingPaymentsSoap, IcelandicOnlineBankingPaymentsSoap.class, features);
    }

}
