package is.netbokhald.li;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.191Z
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", name = "IcelandicOnlineBankingClaimsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IcelandicOnlineBankingClaimsSoap {

    /**
     * Alter existings claims.
     */
    @WebResult(name = "AlterClaimsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "AlterClaims", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.AlterClaims")
    @WebMethod(operationName = "AlterClaims", action = "http://IcelandicOnlineBanking/2005/12/01/AlterClaims")
    @ResponseWrapper(localName = "AlterClaimsResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.AlterClaimsResponse")
    public java.lang.String alterClaims(
        @WebParam(name = "claims", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.ClaimCollection claims
    );

    /**
     * Returns the result of an operation where claims have been created, updated or canceled.
     */
    @WebResult(name = "GetClaimOperationResultResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "GetClaimOperationResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.GetClaimOperationResult")
    @WebMethod(operationName = "GetClaimOperationResult", action = "http://IcelandicOnlineBanking/2005/12/01/GetClaimOperationResult")
    @ResponseWrapper(localName = "GetClaimOperationResultResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.GetClaimOperationResultResponse")
    public is.netbokhald.li.ClaimOperationResult getClaimOperationResult(
        @WebParam(name = "id", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        java.lang.String id
    );

    /**
     * Create a new claim.
     */
    @WebResult(name = "CreateClaimResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "CreateClaim", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CreateClaim")
    @WebMethod(operationName = "CreateClaim", action = "http://IcelandicOnlineBanking/2005/12/01/CreateClaim")
    @ResponseWrapper(localName = "CreateClaimResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CreateClaimResponse")
    public is.netbokhald.li.ClaimOperationResult createClaim(
        @WebParam(name = "claim", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.Claim claim
    );

    /**
     * Alter an existing claim.
     */
    @WebResult(name = "AlterClaimResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "AlterClaim", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.AlterClaim")
    @WebMethod(operationName = "AlterClaim", action = "http://IcelandicOnlineBanking/2005/12/01/AlterClaim")
    @ResponseWrapper(localName = "AlterClaimResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.AlterClaimResponse")
    public is.netbokhald.li.ClaimOperationResult alterClaim(
        @WebParam(name = "claim", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.Claim claim
    );

    /**
     * Cancel a claim corresponding to the unique key.
     */
    @WebResult(name = "CancelClaimResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "CancelClaim", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CancelClaim")
    @WebMethod(operationName = "CancelClaim", action = "http://IcelandicOnlineBanking/2005/12/01/CancelClaim")
    @ResponseWrapper(localName = "CancelClaimResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CancelClaimResponse")
    public is.netbokhald.li.ClaimOperationResult cancelClaim(
        @WebParam(name = "key", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.ClaimKey key
    );

    /**
     * Create new claims.
     */
    @WebResult(name = "CreateClaimsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "CreateClaims", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CreateClaims")
    @WebMethod(operationName = "CreateClaims", action = "http://IcelandicOnlineBanking/2005/12/01/CreateClaims")
    @ResponseWrapper(localName = "CreateClaimsResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CreateClaimsResponse")
    public java.lang.String createClaims(
        @WebParam(name = "claims", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.ClaimCollection claims
    );

    /**
     * Return the payments that fall within the parameters of the query.
     */
    @WebResult(name = "QueryPaymentsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "QueryPayments", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.QueryPayments")
    @WebMethod(operationName = "QueryPayments", action = "http://IcelandicOnlineBanking/2005/12/01/QueryPayments")
    @ResponseWrapper(localName = "QueryPaymentsResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.QueryPaymentsResponse")
    public is.netbokhald.li.QueryPaymentsResult queryPayments(
        @WebParam(name = "query", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.PaymentsQuery query
    );

    /**
     * Return the status of a claim corresponding to a unique key.
     */
    @WebResult(name = "QueryClaimResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "QueryClaim", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.QueryClaim")
    @WebMethod(operationName = "QueryClaim", action = "http://IcelandicOnlineBanking/2005/12/01/QueryClaim")
    @ResponseWrapper(localName = "QueryClaimResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.QueryClaimResponse")
    public is.netbokhald.li.ClaimInfo queryClaim(
        @WebParam(name = "key", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.ClaimKey key
    );

    /**
     * Cancel claims corresponding to the list of unique keys.
     */
    @WebResult(name = "CancelClaimsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "CancelClaims", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CancelClaims")
    @WebMethod(operationName = "CancelClaims", action = "http://IcelandicOnlineBanking/2005/12/01/CancelClaims")
    @ResponseWrapper(localName = "CancelClaimsResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.CancelClaimsResponse")
    public java.lang.String cancelClaims(
        @WebParam(name = "keys", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.ClaimKeyCollection keys
    );

    /**
     * Return the status of claims that fall within the parameters of the query.
     */
    @WebResult(name = "QueryClaimsResult", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
    @RequestWrapper(localName = "QueryClaims", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.QueryClaims")
    @WebMethod(operationName = "QueryClaims", action = "http://IcelandicOnlineBanking/2005/12/01/QueryClaims")
    @ResponseWrapper(localName = "QueryClaimsResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims", className = "is.netbokhald.li.QueryClaimsResponse")
    public is.netbokhald.li.QueryClaimsResult queryClaims(
        @WebParam(name = "query", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Claims")
        is.netbokhald.li.ClaimsQuery query
    );
}
