package is.netbokhald.li;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.185Z
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements", name = "IcelandicOnlineBankingStatementsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IcelandicOnlineBankingStatementsSoap {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CurrencyRateResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements", partName = "parameters")
    @WebMethod(operationName = "GetCurrencyRates", action = "http://IcelandicOnlineBanking/2005/12/01/GetCurrencyRates")
    public CurrencyRateResponse getCurrencyRates(
        @WebParam(partName = "parameters", name = "CurrencyRateRequest", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements")
        CurrencyRateRequest parameters
    );

    @WebResult(name = "accountStatementResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements")
    @RequestWrapper(localName = "GetAccountStatement", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements", className = "is.netbokhald.li.GetAccountStatement")
    @WebMethod(operationName = "GetAccountStatement", action = "http://IcelandicOnlineBanking/2005/12/01/GetAccountStatement")
    @ResponseWrapper(localName = "GetAccountStatementResponse", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements", className = "is.netbokhald.li.GetAccountStatementResponse")
    public is.netbokhald.li.AccountStatementResponse getAccountStatement(
        @WebParam(name = "accountStatement", targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Statements")
        is.netbokhald.li.AccountStatement accountStatement
    );
}
