
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package is.netbokhald.li;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-04-08T14:08:14.162Z
 * Generated source version: 2.7.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "IcelandicOnlineBankingPaymentsService",
                      portName = "IcelandicOnlineBankingPaymentsSoap",
                      targetNamespace = "http://IcelandicOnlineBanking/2005/12/01/Payments",
                      wsdlLocation = "https://b2bws.fbl.is/xsd/IcelandicOnlineBanking.wsdl",
                      endpointInterface = "is.netbokhald.li.IcelandicOnlineBankingPaymentsSoap")
                      
public class IcelandicOnlineBankingPaymentsSoapImpl implements IcelandicOnlineBankingPaymentsSoap {

    private static final Logger LOG = Logger.getLogger(IcelandicOnlineBankingPaymentsSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingPaymentsSoap#doPayment(is.netbokhald.li.Payment  payment )*
     */
    public is.netbokhald.li.PaymentsResult doPayment(is.netbokhald.li.Payment payment) { 
        LOG.info("Executing operation doPayment");
        System.out.println(payment);
        try {
            is.netbokhald.li.PaymentsResult _return = new is.netbokhald.li.PaymentsResult();
            _return.setID("ID521152484");
            is.netbokhald.li.BatchStatus _returnStatus = is.netbokhald.li.BatchStatus.IN_PROGRESS;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.PaymentResultDetails> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.PaymentResultDetails>();
            is.netbokhald.li.PaymentResultDetails _returnSuccessVal1 = new is.netbokhald.li.PaymentResultDetails();
            is.netbokhald.li.ABGiro _returnSuccessVal1ABGiro = new is.netbokhald.li.ABGiro();
            _returnSuccessVal1ABGiro.setAccount("Account-791952393");
            _returnSuccessVal1ABGiro.setReference("Reference1810176993");
            _returnSuccessVal1ABGiro.setBillNumber("BillNumber1879219978");
            _returnSuccessVal1ABGiro.setCategoryCode("CategoryCode-1495527919");
            _returnSuccessVal1.setABGiro(_returnSuccessVal1ABGiro);
            is.netbokhald.li.CGiro _returnSuccessVal1CGiro = new is.netbokhald.li.CGiro();
            _returnSuccessVal1CGiro.setAccount("Account1466077834");
            _returnSuccessVal1CGiro.setAccountOwnerID("AccountOwnerID1667307982");
            _returnSuccessVal1CGiro.setBillNumber("BillNumber-783036935");
            _returnSuccessVal1CGiro.setCategoryCode("CategoryCode-1694808915");
            _returnSuccessVal1.setCGiro(_returnSuccessVal1CGiro);
            is.netbokhald.li.PaymentSlipInfo _returnSuccessVal1PaymentSlip = new is.netbokhald.li.PaymentSlipInfo();
            _returnSuccessVal1PaymentSlip.setAccount("Account-953677096");
            _returnSuccessVal1PaymentSlip.setPersonID("PersonID-1827200541");
            _returnSuccessVal1PaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.172Z"));
            _returnSuccessVal1PaymentSlip.setIsDeposit(false);
            _returnSuccessVal1PaymentSlip.setAmountDue(new java.math.BigDecimal("-5614271143323929792.8170229723151159050"));
            _returnSuccessVal1PaymentSlip.setDefaultCosts(new java.math.BigDecimal("-8534103912406366838.5051013034733780133"));
            _returnSuccessVal1PaymentSlip.setOtherCosts(new java.math.BigDecimal("612901250997957216.284431059779113795"));
            _returnSuccessVal1PaymentSlip.setOtherDefaultCosts(new java.math.BigDecimal("577186718284015612.2404958103055122348"));
            _returnSuccessVal1PaymentSlip.setDefaultInterest(new java.math.BigDecimal("1115077624835870754.9165046497845428823"));
            _returnSuccessVal1PaymentSlip.setNoticeAndPaymentFee(new java.math.BigDecimal("-61164868712580783.7604120554226108137"));
            _returnSuccessVal1PaymentSlip.setDiscount(new java.math.BigDecimal("3861533612693561141.2531701020587550017"));
            _returnSuccessVal1PaymentSlip.setCategoryCode("CategoryCode-422035430");
            _returnSuccessVal1.setPaymentSlip(_returnSuccessVal1PaymentSlip);
            is.netbokhald.li.Transfer _returnSuccessVal1Transfer = new is.netbokhald.li.Transfer();
            _returnSuccessVal1Transfer.setAccount("Account-2145384865");
            _returnSuccessVal1Transfer.setAccountOwnerID("AccountOwnerID-719294306");
            _returnSuccessVal1Transfer.setCategoryCode("CategoryCode-136901322");
            _returnSuccessVal1Transfer.setReference("Reference-86083018");
            _returnSuccessVal1Transfer.setBillNumber("BillNumber-1887035593");
            _returnSuccessVal1.setTransfer(_returnSuccessVal1Transfer);
            _returnSuccessVal1.setAmount(new java.math.BigDecimal("6698055496334318370.6599307273465439280"));
            is.netbokhald.li.Communication _returnSuccessVal1Receipt = new is.netbokhald.li.Communication();
            is.netbokhald.li.Communication.PostalMail _returnSuccessVal1ReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
            _returnSuccessVal1ReceiptPostalMail.setLanguage("Language1768832138");
            is.netbokhald.li.Address _returnSuccessVal1ReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setName("Name295209037");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine11727183293");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine2-1880053954");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber-82297670");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setCity("City1253321136");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setRegion("Region-2043631703");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setCountry("Country1752842884");
            _returnSuccessVal1ReceiptPostalMail.setReceiverAddress(_returnSuccessVal1ReceiptPostalMailReceiverAddress);
            _returnSuccessVal1ReceiptPostalMail.setUsePersonID(Boolean.valueOf(true));
            _returnSuccessVal1Receipt.setPostalMail(_returnSuccessVal1ReceiptPostalMail);
            java.util.List<is.netbokhald.li.Communication.EMail> _returnSuccessVal1ReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
            _returnSuccessVal1Receipt.getEMail().addAll(_returnSuccessVal1ReceiptEMail);
            java.util.List<is.netbokhald.li.Communication.SMS> _returnSuccessVal1ReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
            _returnSuccessVal1Receipt.getSMS().addAll(_returnSuccessVal1ReceiptSMS);
            _returnSuccessVal1.setReceipt(_returnSuccessVal1Receipt);
            _returnSuccessVal1.setDescription("Description1510879691");
            _returnSuccessVal1.setBookingID("BookingID1165565755");
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.PaymentError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.PaymentError>();
            is.netbokhald.li.PaymentError _returnErrorsVal1 = new is.netbokhald.li.PaymentError();
            is.netbokhald.li.PaymentIn _returnErrorsVal1Payment = new is.netbokhald.li.PaymentIn();
            is.netbokhald.li.ABGiro _returnErrorsVal1PaymentABGiro = new is.netbokhald.li.ABGiro();
            _returnErrorsVal1PaymentABGiro.setAccount("Account1699749970");
            _returnErrorsVal1PaymentABGiro.setReference("Reference-1742617264");
            _returnErrorsVal1PaymentABGiro.setBillNumber("BillNumber1838054325");
            _returnErrorsVal1PaymentABGiro.setCategoryCode("CategoryCode-1092191315");
            _returnErrorsVal1Payment.setABGiro(_returnErrorsVal1PaymentABGiro);
            is.netbokhald.li.CGiro _returnErrorsVal1PaymentCGiro = new is.netbokhald.li.CGiro();
            _returnErrorsVal1PaymentCGiro.setAccount("Account3247694");
            _returnErrorsVal1PaymentCGiro.setAccountOwnerID("AccountOwnerID-288193784");
            _returnErrorsVal1PaymentCGiro.setBillNumber("BillNumber-782765196");
            _returnErrorsVal1PaymentCGiro.setCategoryCode("CategoryCode-1792707397");
            _returnErrorsVal1Payment.setCGiro(_returnErrorsVal1PaymentCGiro);
            is.netbokhald.li.PaymentSlip _returnErrorsVal1PaymentPaymentSlip = new is.netbokhald.li.PaymentSlip();
            _returnErrorsVal1PaymentPaymentSlip.setAccount("Account-1850142736");
            _returnErrorsVal1PaymentPaymentSlip.setPersonID("PersonID1214197134");
            _returnErrorsVal1PaymentPaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.174Z"));
            _returnErrorsVal1PaymentPaymentSlip.setIsDeposit(true);
            _returnErrorsVal1Payment.setPaymentSlip(_returnErrorsVal1PaymentPaymentSlip);
            is.netbokhald.li.Transfer _returnErrorsVal1PaymentTransfer = new is.netbokhald.li.Transfer();
            _returnErrorsVal1PaymentTransfer.setAccount("Account-311756118");
            _returnErrorsVal1PaymentTransfer.setAccountOwnerID("AccountOwnerID-295263181");
            _returnErrorsVal1PaymentTransfer.setCategoryCode("CategoryCode429032282");
            _returnErrorsVal1PaymentTransfer.setReference("Reference-1754689568");
            _returnErrorsVal1PaymentTransfer.setBillNumber("BillNumber-232960373");
            _returnErrorsVal1Payment.setTransfer(_returnErrorsVal1PaymentTransfer);
            _returnErrorsVal1Payment.setAmount(new java.math.BigDecimal("5412256415365554472.8410601690134207168"));
            is.netbokhald.li.Communication _returnErrorsVal1PaymentReceipt = new is.netbokhald.li.Communication();
            is.netbokhald.li.Communication.PostalMail _returnErrorsVal1PaymentReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
            _returnErrorsVal1PaymentReceiptPostalMail.setLanguage("Language-1145089266");
            is.netbokhald.li.Address _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setName("Name-1163151328");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine12094360825");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine21755680703");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber976414208");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setCity("City2137276982");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setRegion("Region583810840");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setCountry("Country-1176123114");
            _returnErrorsVal1PaymentReceiptPostalMail.setReceiverAddress(_returnErrorsVal1PaymentReceiptPostalMailReceiverAddress);
            _returnErrorsVal1PaymentReceiptPostalMail.setUsePersonID(Boolean.valueOf(true));
            _returnErrorsVal1PaymentReceipt.setPostalMail(_returnErrorsVal1PaymentReceiptPostalMail);
            java.util.List<is.netbokhald.li.Communication.EMail> _returnErrorsVal1PaymentReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
            _returnErrorsVal1PaymentReceipt.getEMail().addAll(_returnErrorsVal1PaymentReceiptEMail);
            java.util.List<is.netbokhald.li.Communication.SMS> _returnErrorsVal1PaymentReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
            _returnErrorsVal1PaymentReceipt.getSMS().addAll(_returnErrorsVal1PaymentReceiptSMS);
            _returnErrorsVal1Payment.setReceipt(_returnErrorsVal1PaymentReceipt);
            _returnErrorsVal1Payment.setDescription("Description1838454995");
            _returnErrorsVal1Payment.setBookingID("BookingID-826698111");
            _returnErrorsVal1.setPayment(_returnErrorsVal1Payment);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code155975342");
            _returnErrorsVal1Error.setMessage("Message-778148816");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            _return.setDateOfPayment(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.176Z"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingPaymentsSoap#getPaymentsResult(java.lang.String  paymentID ,)is.netbokhald.li.PaymentsStatus  filter )*
     */
    public is.netbokhald.li.PaymentsResult getPaymentsResult(java.lang.String paymentID,is.netbokhald.li.PaymentsStatus filter) { 
        LOG.info("Executing operation getPaymentsResult");
        System.out.println(paymentID);
        System.out.println(filter);
        try {
            is.netbokhald.li.PaymentsResult _return = new is.netbokhald.li.PaymentsResult();
            _return.setID("ID1342804405");
            is.netbokhald.li.BatchStatus _returnStatus = is.netbokhald.li.BatchStatus.COMPLETED;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.PaymentResultDetails> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.PaymentResultDetails>();
            is.netbokhald.li.PaymentResultDetails _returnSuccessVal1 = new is.netbokhald.li.PaymentResultDetails();
            is.netbokhald.li.ABGiro _returnSuccessVal1ABGiro = new is.netbokhald.li.ABGiro();
            _returnSuccessVal1ABGiro.setAccount("Account-1329936813");
            _returnSuccessVal1ABGiro.setReference("Reference-1071976169");
            _returnSuccessVal1ABGiro.setBillNumber("BillNumber-280099310");
            _returnSuccessVal1ABGiro.setCategoryCode("CategoryCode-1580643190");
            _returnSuccessVal1.setABGiro(_returnSuccessVal1ABGiro);
            is.netbokhald.li.CGiro _returnSuccessVal1CGiro = new is.netbokhald.li.CGiro();
            _returnSuccessVal1CGiro.setAccount("Account-872486541");
            _returnSuccessVal1CGiro.setAccountOwnerID("AccountOwnerID-490484380");
            _returnSuccessVal1CGiro.setBillNumber("BillNumber-1650956285");
            _returnSuccessVal1CGiro.setCategoryCode("CategoryCode87468489");
            _returnSuccessVal1.setCGiro(_returnSuccessVal1CGiro);
            is.netbokhald.li.PaymentSlipInfo _returnSuccessVal1PaymentSlip = new is.netbokhald.li.PaymentSlipInfo();
            _returnSuccessVal1PaymentSlip.setAccount("Account983012133");
            _returnSuccessVal1PaymentSlip.setPersonID("PersonID1713680253");
            _returnSuccessVal1PaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.177Z"));
            _returnSuccessVal1PaymentSlip.setIsDeposit(true);
            _returnSuccessVal1PaymentSlip.setAmountDue(new java.math.BigDecimal("-6508666850815714707.9020431724799278439"));
            _returnSuccessVal1PaymentSlip.setDefaultCosts(new java.math.BigDecimal("-3715906748712866626.3785234033691109729"));
            _returnSuccessVal1PaymentSlip.setOtherCosts(new java.math.BigDecimal("-5246615424710845249.3784801939937985159"));
            _returnSuccessVal1PaymentSlip.setOtherDefaultCosts(new java.math.BigDecimal("3799659709748435281.5390227236484676895"));
            _returnSuccessVal1PaymentSlip.setDefaultInterest(new java.math.BigDecimal("-216036593321127727.6892500412261086993"));
            _returnSuccessVal1PaymentSlip.setNoticeAndPaymentFee(new java.math.BigDecimal("-8102258491670051686.1427011965976772813"));
            _returnSuccessVal1PaymentSlip.setDiscount(new java.math.BigDecimal("6334056413099282637.5211285138820660113"));
            _returnSuccessVal1PaymentSlip.setCategoryCode("CategoryCode2136007898");
            _returnSuccessVal1.setPaymentSlip(_returnSuccessVal1PaymentSlip);
            is.netbokhald.li.Transfer _returnSuccessVal1Transfer = new is.netbokhald.li.Transfer();
            _returnSuccessVal1Transfer.setAccount("Account1843473491");
            _returnSuccessVal1Transfer.setAccountOwnerID("AccountOwnerID600811365");
            _returnSuccessVal1Transfer.setCategoryCode("CategoryCode1059281143");
            _returnSuccessVal1Transfer.setReference("Reference1422445298");
            _returnSuccessVal1Transfer.setBillNumber("BillNumber-1143823069");
            _returnSuccessVal1.setTransfer(_returnSuccessVal1Transfer);
            _returnSuccessVal1.setAmount(new java.math.BigDecimal("3934978242995234624.4133786028140258112"));
            is.netbokhald.li.Communication _returnSuccessVal1Receipt = new is.netbokhald.li.Communication();
            is.netbokhald.li.Communication.PostalMail _returnSuccessVal1ReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
            _returnSuccessVal1ReceiptPostalMail.setLanguage("Language-1898973678");
            is.netbokhald.li.Address _returnSuccessVal1ReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setName("Name-1888641706");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine1-1680187649");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine2-1741600507");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber427343828");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setCity("City-1565633741");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setRegion("Region235951730");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setCountry("Country1249033508");
            _returnSuccessVal1ReceiptPostalMail.setReceiverAddress(_returnSuccessVal1ReceiptPostalMailReceiverAddress);
            _returnSuccessVal1ReceiptPostalMail.setUsePersonID(Boolean.valueOf(false));
            _returnSuccessVal1Receipt.setPostalMail(_returnSuccessVal1ReceiptPostalMail);
            java.util.List<is.netbokhald.li.Communication.EMail> _returnSuccessVal1ReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
            _returnSuccessVal1Receipt.getEMail().addAll(_returnSuccessVal1ReceiptEMail);
            java.util.List<is.netbokhald.li.Communication.SMS> _returnSuccessVal1ReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
            _returnSuccessVal1Receipt.getSMS().addAll(_returnSuccessVal1ReceiptSMS);
            _returnSuccessVal1.setReceipt(_returnSuccessVal1Receipt);
            _returnSuccessVal1.setDescription("Description87628932");
            _returnSuccessVal1.setBookingID("BookingID231228231");
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.PaymentError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.PaymentError>();
            is.netbokhald.li.PaymentError _returnErrorsVal1 = new is.netbokhald.li.PaymentError();
            is.netbokhald.li.PaymentIn _returnErrorsVal1Payment = new is.netbokhald.li.PaymentIn();
            is.netbokhald.li.ABGiro _returnErrorsVal1PaymentABGiro = new is.netbokhald.li.ABGiro();
            _returnErrorsVal1PaymentABGiro.setAccount("Account1786150635");
            _returnErrorsVal1PaymentABGiro.setReference("Reference878885273");
            _returnErrorsVal1PaymentABGiro.setBillNumber("BillNumber-1448351351");
            _returnErrorsVal1PaymentABGiro.setCategoryCode("CategoryCode-493693851");
            _returnErrorsVal1Payment.setABGiro(_returnErrorsVal1PaymentABGiro);
            is.netbokhald.li.CGiro _returnErrorsVal1PaymentCGiro = new is.netbokhald.li.CGiro();
            _returnErrorsVal1PaymentCGiro.setAccount("Account-1821627319");
            _returnErrorsVal1PaymentCGiro.setAccountOwnerID("AccountOwnerID-2087150420");
            _returnErrorsVal1PaymentCGiro.setBillNumber("BillNumber-2131013058");
            _returnErrorsVal1PaymentCGiro.setCategoryCode("CategoryCode1556772990");
            _returnErrorsVal1Payment.setCGiro(_returnErrorsVal1PaymentCGiro);
            is.netbokhald.li.PaymentSlip _returnErrorsVal1PaymentPaymentSlip = new is.netbokhald.li.PaymentSlip();
            _returnErrorsVal1PaymentPaymentSlip.setAccount("Account-277646063");
            _returnErrorsVal1PaymentPaymentSlip.setPersonID("PersonID1614091543");
            _returnErrorsVal1PaymentPaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.179Z"));
            _returnErrorsVal1PaymentPaymentSlip.setIsDeposit(true);
            _returnErrorsVal1Payment.setPaymentSlip(_returnErrorsVal1PaymentPaymentSlip);
            is.netbokhald.li.Transfer _returnErrorsVal1PaymentTransfer = new is.netbokhald.li.Transfer();
            _returnErrorsVal1PaymentTransfer.setAccount("Account1617135015");
            _returnErrorsVal1PaymentTransfer.setAccountOwnerID("AccountOwnerID708570365");
            _returnErrorsVal1PaymentTransfer.setCategoryCode("CategoryCode345227026");
            _returnErrorsVal1PaymentTransfer.setReference("Reference-502339608");
            _returnErrorsVal1PaymentTransfer.setBillNumber("BillNumber-186726870");
            _returnErrorsVal1Payment.setTransfer(_returnErrorsVal1PaymentTransfer);
            _returnErrorsVal1Payment.setAmount(new java.math.BigDecimal("-3368276957397650129.5252128705653210779"));
            is.netbokhald.li.Communication _returnErrorsVal1PaymentReceipt = new is.netbokhald.li.Communication();
            is.netbokhald.li.Communication.PostalMail _returnErrorsVal1PaymentReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
            _returnErrorsVal1PaymentReceiptPostalMail.setLanguage("Language-1268063601");
            is.netbokhald.li.Address _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setName("Name232265351");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine1-1352252154");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine21940078889");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber35930329");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setCity("City684751925");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setRegion("Region-483627579");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setCountry("Country-1257561547");
            _returnErrorsVal1PaymentReceiptPostalMail.setReceiverAddress(_returnErrorsVal1PaymentReceiptPostalMailReceiverAddress);
            _returnErrorsVal1PaymentReceiptPostalMail.setUsePersonID(Boolean.valueOf(true));
            _returnErrorsVal1PaymentReceipt.setPostalMail(_returnErrorsVal1PaymentReceiptPostalMail);
            java.util.List<is.netbokhald.li.Communication.EMail> _returnErrorsVal1PaymentReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
            _returnErrorsVal1PaymentReceipt.getEMail().addAll(_returnErrorsVal1PaymentReceiptEMail);
            java.util.List<is.netbokhald.li.Communication.SMS> _returnErrorsVal1PaymentReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
            _returnErrorsVal1PaymentReceipt.getSMS().addAll(_returnErrorsVal1PaymentReceiptSMS);
            _returnErrorsVal1Payment.setReceipt(_returnErrorsVal1PaymentReceipt);
            _returnErrorsVal1Payment.setDescription("Description1606668808");
            _returnErrorsVal1Payment.setBookingID("BookingID550481860");
            _returnErrorsVal1.setPayment(_returnErrorsVal1Payment);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code-980737496");
            _returnErrorsVal1Error.setMessage("Message1656763974");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            _return.setDateOfPayment(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.180Z"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingPaymentsSoap#getPaymentResult(java.lang.String  paymentID )*
     */
    public is.netbokhald.li.PaymentsResult getPaymentResult(java.lang.String paymentID) { 
        LOG.info("Executing operation getPaymentResult");
        System.out.println(paymentID);
        try {
            is.netbokhald.li.PaymentsResult _return = new is.netbokhald.li.PaymentsResult();
            _return.setID("ID284280435");
            is.netbokhald.li.BatchStatus _returnStatus = is.netbokhald.li.BatchStatus.COMPLETED_WITH_ERRORS;
            _return.setStatus(_returnStatus);
            java.util.List<is.netbokhald.li.PaymentResultDetails> _returnSuccess = new java.util.ArrayList<is.netbokhald.li.PaymentResultDetails>();
            is.netbokhald.li.PaymentResultDetails _returnSuccessVal1 = new is.netbokhald.li.PaymentResultDetails();
            is.netbokhald.li.ABGiro _returnSuccessVal1ABGiro = new is.netbokhald.li.ABGiro();
            _returnSuccessVal1ABGiro.setAccount("Account-243408767");
            _returnSuccessVal1ABGiro.setReference("Reference897333034");
            _returnSuccessVal1ABGiro.setBillNumber("BillNumber1977107912");
            _returnSuccessVal1ABGiro.setCategoryCode("CategoryCode-747831953");
            _returnSuccessVal1.setABGiro(_returnSuccessVal1ABGiro);
            is.netbokhald.li.CGiro _returnSuccessVal1CGiro = new is.netbokhald.li.CGiro();
            _returnSuccessVal1CGiro.setAccount("Account996666412");
            _returnSuccessVal1CGiro.setAccountOwnerID("AccountOwnerID-1542003577");
            _returnSuccessVal1CGiro.setBillNumber("BillNumber-1132809051");
            _returnSuccessVal1CGiro.setCategoryCode("CategoryCode1103933462");
            _returnSuccessVal1.setCGiro(_returnSuccessVal1CGiro);
            is.netbokhald.li.PaymentSlipInfo _returnSuccessVal1PaymentSlip = new is.netbokhald.li.PaymentSlipInfo();
            _returnSuccessVal1PaymentSlip.setAccount("Account-34126566");
            _returnSuccessVal1PaymentSlip.setPersonID("PersonID1457455081");
            _returnSuccessVal1PaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.181Z"));
            _returnSuccessVal1PaymentSlip.setIsDeposit(false);
            _returnSuccessVal1PaymentSlip.setAmountDue(new java.math.BigDecimal("7368120959691186957.3601586855833273980"));
            _returnSuccessVal1PaymentSlip.setDefaultCosts(new java.math.BigDecimal("3366662687530374579.9176301995560804396"));
            _returnSuccessVal1PaymentSlip.setOtherCosts(new java.math.BigDecimal("3887580069772841462.1653089905394730267"));
            _returnSuccessVal1PaymentSlip.setOtherDefaultCosts(new java.math.BigDecimal("-6064959178505174894.1458983009483620599"));
            _returnSuccessVal1PaymentSlip.setDefaultInterest(new java.math.BigDecimal("8156347310638506471.3937667976154119581"));
            _returnSuccessVal1PaymentSlip.setNoticeAndPaymentFee(new java.math.BigDecimal("-6823141490403353840.2173729009716804944"));
            _returnSuccessVal1PaymentSlip.setDiscount(new java.math.BigDecimal("-3943981845057028045.1118597538162095219"));
            _returnSuccessVal1PaymentSlip.setCategoryCode("CategoryCode1853852701");
            _returnSuccessVal1.setPaymentSlip(_returnSuccessVal1PaymentSlip);
            is.netbokhald.li.Transfer _returnSuccessVal1Transfer = new is.netbokhald.li.Transfer();
            _returnSuccessVal1Transfer.setAccount("Account1596682266");
            _returnSuccessVal1Transfer.setAccountOwnerID("AccountOwnerID823563233");
            _returnSuccessVal1Transfer.setCategoryCode("CategoryCode1428528735");
            _returnSuccessVal1Transfer.setReference("Reference348920374");
            _returnSuccessVal1Transfer.setBillNumber("BillNumber1311593730");
            _returnSuccessVal1.setTransfer(_returnSuccessVal1Transfer);
            _returnSuccessVal1.setAmount(new java.math.BigDecimal("4020521547705922412.7405483189514165939"));
            is.netbokhald.li.Communication _returnSuccessVal1Receipt = new is.netbokhald.li.Communication();
            is.netbokhald.li.Communication.PostalMail _returnSuccessVal1ReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
            _returnSuccessVal1ReceiptPostalMail.setLanguage("Language-289971531");
            is.netbokhald.li.Address _returnSuccessVal1ReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setName("Name853813793");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine11421158330");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine21396918736");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber1945032779");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setCity("City-459322066");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setRegion("Region722557621");
            _returnSuccessVal1ReceiptPostalMailReceiverAddress.setCountry("Country158861424");
            _returnSuccessVal1ReceiptPostalMail.setReceiverAddress(_returnSuccessVal1ReceiptPostalMailReceiverAddress);
            _returnSuccessVal1ReceiptPostalMail.setUsePersonID(Boolean.valueOf(false));
            _returnSuccessVal1Receipt.setPostalMail(_returnSuccessVal1ReceiptPostalMail);
            java.util.List<is.netbokhald.li.Communication.EMail> _returnSuccessVal1ReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
            _returnSuccessVal1Receipt.getEMail().addAll(_returnSuccessVal1ReceiptEMail);
            java.util.List<is.netbokhald.li.Communication.SMS> _returnSuccessVal1ReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
            _returnSuccessVal1Receipt.getSMS().addAll(_returnSuccessVal1ReceiptSMS);
            _returnSuccessVal1.setReceipt(_returnSuccessVal1Receipt);
            _returnSuccessVal1.setDescription("Description-1043022027");
            _returnSuccessVal1.setBookingID("BookingID-1378836674");
            _returnSuccess.add(_returnSuccessVal1);
            _return.getSuccess().addAll(_returnSuccess);
            java.util.List<is.netbokhald.li.PaymentError> _returnErrors = new java.util.ArrayList<is.netbokhald.li.PaymentError>();
            is.netbokhald.li.PaymentError _returnErrorsVal1 = new is.netbokhald.li.PaymentError();
            is.netbokhald.li.PaymentIn _returnErrorsVal1Payment = new is.netbokhald.li.PaymentIn();
            is.netbokhald.li.ABGiro _returnErrorsVal1PaymentABGiro = new is.netbokhald.li.ABGiro();
            _returnErrorsVal1PaymentABGiro.setAccount("Account1689198572");
            _returnErrorsVal1PaymentABGiro.setReference("Reference101501404");
            _returnErrorsVal1PaymentABGiro.setBillNumber("BillNumber-1840103747");
            _returnErrorsVal1PaymentABGiro.setCategoryCode("CategoryCode-158002980");
            _returnErrorsVal1Payment.setABGiro(_returnErrorsVal1PaymentABGiro);
            is.netbokhald.li.CGiro _returnErrorsVal1PaymentCGiro = new is.netbokhald.li.CGiro();
            _returnErrorsVal1PaymentCGiro.setAccount("Account-1599565830");
            _returnErrorsVal1PaymentCGiro.setAccountOwnerID("AccountOwnerID-1452330593");
            _returnErrorsVal1PaymentCGiro.setBillNumber("BillNumber1500263788");
            _returnErrorsVal1PaymentCGiro.setCategoryCode("CategoryCode330375473");
            _returnErrorsVal1Payment.setCGiro(_returnErrorsVal1PaymentCGiro);
            is.netbokhald.li.PaymentSlip _returnErrorsVal1PaymentPaymentSlip = new is.netbokhald.li.PaymentSlip();
            _returnErrorsVal1PaymentPaymentSlip.setAccount("Account-112748806");
            _returnErrorsVal1PaymentPaymentSlip.setPersonID("PersonID660189737");
            _returnErrorsVal1PaymentPaymentSlip.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.183Z"));
            _returnErrorsVal1PaymentPaymentSlip.setIsDeposit(true);
            _returnErrorsVal1Payment.setPaymentSlip(_returnErrorsVal1PaymentPaymentSlip);
            is.netbokhald.li.Transfer _returnErrorsVal1PaymentTransfer = new is.netbokhald.li.Transfer();
            _returnErrorsVal1PaymentTransfer.setAccount("Account-2090616995");
            _returnErrorsVal1PaymentTransfer.setAccountOwnerID("AccountOwnerID-812652656");
            _returnErrorsVal1PaymentTransfer.setCategoryCode("CategoryCode-1357522005");
            _returnErrorsVal1PaymentTransfer.setReference("Reference-728281010");
            _returnErrorsVal1PaymentTransfer.setBillNumber("BillNumber-1817419356");
            _returnErrorsVal1Payment.setTransfer(_returnErrorsVal1PaymentTransfer);
            _returnErrorsVal1Payment.setAmount(new java.math.BigDecimal("1641601036413116898.3852712547543055693"));
            is.netbokhald.li.Communication _returnErrorsVal1PaymentReceipt = new is.netbokhald.li.Communication();
            is.netbokhald.li.Communication.PostalMail _returnErrorsVal1PaymentReceiptPostalMail = new is.netbokhald.li.Communication.PostalMail();
            _returnErrorsVal1PaymentReceiptPostalMail.setLanguage("Language130592642");
            is.netbokhald.li.Address _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress = new is.netbokhald.li.Address();
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setName("Name380051612");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setAddressLine1("AddressLine11495335318");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setAddressLine2("AddressLine21763997901");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setPostCodeNumber("PostCodeNumber156972318");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setCity("City-1376967558");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setRegion("Region-1621673194");
            _returnErrorsVal1PaymentReceiptPostalMailReceiverAddress.setCountry("Country1024627749");
            _returnErrorsVal1PaymentReceiptPostalMail.setReceiverAddress(_returnErrorsVal1PaymentReceiptPostalMailReceiverAddress);
            _returnErrorsVal1PaymentReceiptPostalMail.setUsePersonID(Boolean.valueOf(true));
            _returnErrorsVal1PaymentReceipt.setPostalMail(_returnErrorsVal1PaymentReceiptPostalMail);
            java.util.List<is.netbokhald.li.Communication.EMail> _returnErrorsVal1PaymentReceiptEMail = new java.util.ArrayList<is.netbokhald.li.Communication.EMail>();
            _returnErrorsVal1PaymentReceipt.getEMail().addAll(_returnErrorsVal1PaymentReceiptEMail);
            java.util.List<is.netbokhald.li.Communication.SMS> _returnErrorsVal1PaymentReceiptSMS = new java.util.ArrayList<is.netbokhald.li.Communication.SMS>();
            _returnErrorsVal1PaymentReceipt.getSMS().addAll(_returnErrorsVal1PaymentReceiptSMS);
            _returnErrorsVal1Payment.setReceipt(_returnErrorsVal1PaymentReceipt);
            _returnErrorsVal1Payment.setDescription("Description145161206");
            _returnErrorsVal1Payment.setBookingID("BookingID-1414628430");
            _returnErrorsVal1.setPayment(_returnErrorsVal1Payment);
            is.netbokhald.li.Error _returnErrorsVal1Error = new is.netbokhald.li.Error();
            _returnErrorsVal1Error.setCode("Code1182450567");
            _returnErrorsVal1Error.setMessage("Message-1632186976");
            _returnErrorsVal1.setError(_returnErrorsVal1Error);
            _returnErrors.add(_returnErrorsVal1);
            _return.getErrors().addAll(_returnErrors);
            _return.setDateOfPayment(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T14:08:14.184Z"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see is.netbokhald.li.IcelandicOnlineBankingPaymentsSoap#doPayments(is.netbokhald.li.Payments  payments )*
     */
    public java.lang.String doPayments(is.netbokhald.li.Payments payments) { 
        LOG.info("Executing operation doPayments");
        System.out.println(payments);
        try {
            java.lang.String _return = "_return-1911991129";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
