<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Innskra" targetNamespace="http://is.fbl.b2b/innskra" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" id="LI_InnskraDataSet" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="https://b2b.fbl.is/schema/LI_Common_types.xsd"/>
	<xs:element name="LI_Innskra">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="notandanafn" type="LI_notandanafn_type"/>
				<xs:element name="lykilord" type="LI_lykilord_type"/>
				<xs:element minOccurs="0" name="sid">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="256"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>
  </wsdl:types>
</wsdl:definitions>
